#include "bloom.h"
#include "city.h"
#include <iostream>

using namespace std;

int main() {
  BloomFilter *new_b = new BloomFilter(128);
  new_b->add_string("Liam");
  new_b->add_string("Noah");
  new_b->add_string("Oliver");
  new_b->add_string("William");
  new_b->add_string("Elijah");
  new_b->add_string("James");
  new_b->add_string("Benjamin");
  new_b->add_string("Lucas");
  new_b->add_string("Mason");
  new_b->add_string("Ethan");
  new_b->add_string("Alexander");
  new_b->add_string("Henry");
  new_b->add_string("Jacob");
  new_b->add_string("Michael");
  new_b->add_string("Daniel");
  new_b->add_string("Logan");
  new_b->add_string("Jackson");
  new_b->add_string("Sebastian");
  new_b->add_string("Jack");
  new_b->add_string("Aiden");
  new_b->add_string("Owen");
  new_b->add_string("Samuel");
  new_b->add_string("Matthew");
  new_b->add_string("Joseph");
  new_b->add_string("Levi");
  new_b->add_string("Mateo");
  new_b->add_string("David");
  new_b->add_string("John");
  new_b->add_string("Wyatt");
  new_b->add_string("Carter");
  new_b->add_string("Julian");
  new_b->add_string("Luke");
  new_b->add_string("Grayson");
  new_b->add_string("Isaac");
  new_b->add_string("Jayden");
  new_b->add_string("Theodore");
  new_b->add_string("Gabriel");
  new_b->add_string("Anthony");
  new_b->add_string("Dylan");
  new_b->add_string("Leo");
  new_b->add_string("Lincoln");
  new_b->add_string("Jaxon");
  new_b->add_string("Asher");
  new_b->add_string("Christopher");
  new_b->add_string("Josiah");
  new_b->add_string("Andrew");
  new_b->add_string("Thomas");
  new_b->add_string("Joshua");
  new_b->add_string("Ezra");
  new_b->add_string("Hudson");
  new_b->add_string("Charles");
  new_b->add_string("Caleb");
  new_b->add_string("Isaiah");
  new_b->add_string("Ryan");
  new_b->add_string("Nathan");
  new_b->add_string("Adrian");
  new_b->add_string("Christian");
  new_b->add_string("Maverick");
  new_b->add_string("Colton");
  new_b->add_string("Elias");
  new_b->add_string("Aaron");
  new_b->add_string("Eli");
  new_b->add_string("Landon");
  new_b->add_string("Jonathan");
  new_b->add_string("Nolan");
  new_b->add_string("Hunter");
  new_b->add_string("Cameron");
  new_b->add_string("Connor");
  new_b->add_string("Santiago");
  new_b->add_string("Jeremiah");
  new_b->add_string("Ezekiel");
  new_b->add_string("Angel");
  new_b->add_string("Roman");
  new_b->add_string("Easton");
  new_b->add_string("Miles");
  new_b->add_string("Robert");
  new_b->add_string("Jameson");
  new_b->add_string("Nicholas");
  new_b->add_string("Greyson");
  new_b->add_string("Cooper");
  new_b->add_string("Ian");
  new_b->add_string("Carson");
  new_b->add_string("Axel");
  new_b->add_string("Jaxson");
  new_b->add_string("Dominic");
  new_b->add_string("Leonardo");
  new_b->add_string("Luca");
  new_b->add_string("Austin");
  new_b->add_string("Jordan");
  new_b->add_string("Adam");
  new_b->add_string("Xavier");
  new_b->add_string("Jose");
  new_b->add_string("Jace");
  new_b->add_string("Everett");
  new_b->add_string("Declan");
  new_b->add_string("Evan");
  new_b->add_string("Kayden");
  new_b->add_string("Parker");
  new_b->add_string("Wesley");
  new_b->add_string("Kai");
  new_b->add_string("Brayden");
  new_b->add_string("Bryson");
  new_b->add_string("Weston");
  new_b->add_string("Jason");
  new_b->add_string("Emmett");
  new_b->add_string("Sawyer");
  new_b->add_string("Silas");
  new_b->add_string("Bennett");
  new_b->add_string("Brooks");
  new_b->add_string("Micah");
  new_b->add_string("Damian");
  new_b->add_string("Harrison");
  new_b->add_string("Waylon");
  new_b->add_string("Ayden");
  new_b->add_string("Vincent");
  new_b->add_string("Ryder");
  new_b->add_string("Kingston");
  new_b->add_string("Rowan");
  new_b->add_string("George");
  new_b->add_string("Luis");
  new_b->add_string("Chase");
  new_b->add_string("Cole");
  new_b->add_string("Nathaniel");
  new_b->add_string("Zachary");
  new_b->add_string("Ashton");
  new_b->add_string("Braxton");
  new_b->add_string("Gavin");
  new_b->add_string("Tyler");
  new_b->add_string("Diego");
  new_b->add_string("Bentley");
  new_b->add_string("Amir");
  new_b->add_string("Beau");
  new_b->add_string("Gael");
  new_b->add_string("Carlos");
  new_b->add_string("Ryker");
  new_b->add_string("Jasper");
  new_b->add_string("Max");
  new_b->add_string("Juan");
  new_b->add_string("Ivan");
  new_b->add_string("Brandon");
  new_b->add_string("Jonah");
  new_b->add_string("Giovanni");
  new_b->add_string("Kaiden");
  new_b->add_string("Myles");
  new_b->add_string("Calvin");
  new_b->add_string("Lorenzo");
  new_b->add_string("Maxwell");
  new_b->add_string("Jayce");
  new_b->add_string("Kevin");
  new_b->add_string("Legend");
  new_b->add_string("Tristan");
  new_b->add_string("Jesus");
  new_b->add_string("Jude");
  new_b->add_string("Zion");
  new_b->add_string("Justin");
  new_b->add_string("Maddox");
  new_b->add_string("Abel");
  new_b->add_string("King");
  new_b->add_string("Camden");
  new_b->add_string("Elliott");
  new_b->add_string("Malachi");
  new_b->add_string("Milo");
  new_b->add_string("Emmanuel");
  new_b->add_string("Karter");
  new_b->add_string("Rhett");
  new_b->add_string("Alex");
  new_b->add_string("August");
  new_b->add_string("River");
  new_b->add_string("Xander");
  new_b->add_string("Antonio");
  new_b->add_string("Brody");
  new_b->add_string("Finn");
  new_b->add_string("Elliot");
  new_b->add_string("Dean");
  new_b->add_string("Emiliano");
  new_b->add_string("Eric");
  new_b->add_string("Miguel");
  new_b->add_string("Arthur");
  new_b->add_string("Matteo");
  new_b->add_string("Graham");
  new_b->add_string("Alan");
  new_b->add_string("Nicolas");
  new_b->add_string("Blake");
  new_b->add_string("Thiago");
  new_b->add_string("Adriel");
  new_b->add_string("Victor");
  new_b->add_string("Joel");
  new_b->add_string("Timothy");
  new_b->add_string("Hayden");
  new_b->add_string("Judah");
  new_b->add_string("Abraham");
  new_b->add_string("Edward");
  new_b->add_string("Messiah");
  new_b->add_string("Zayden");
  new_b->add_string("Theo");
  new_b->add_string("Tucker");
  new_b->add_string("Grant");
  new_b->add_string("Richard");
  new_b->add_string("Alejandro");
  new_b->add_string("Steven");
  new_b->add_string("Jesse");
  new_b->add_string("Dawson");
  new_b->add_string("Bryce");
  new_b->add_string("Avery");
  new_b->add_string("Oscar");
  new_b->add_string("Patrick");
  new_b->add_string("Archer");
  new_b->add_string("Barrett");
  new_b->add_string("Leon");
  new_b->add_string("Colt");
  new_b->add_string("Charlie");
  new_b->add_string("Peter");
  new_b->add_string("Kaleb");
  new_b->add_string("Lukas");
  new_b->add_string("Beckett");
  new_b->add_string("Jeremy");
  new_b->add_string("Preston");
  new_b->add_string("Enzo");
  new_b->add_string("Luka");
  new_b->add_string("Andres");
  new_b->add_string("Marcus");
  new_b->add_string("Felix");
  new_b->add_string("Mark");
  new_b->add_string("Ace");
  new_b->add_string("Brantley");
  new_b->add_string("Atlas");
  new_b->add_string("Remington");
  new_b->add_string("Maximus");
  new_b->add_string("Matias");
  new_b->add_string("Walker");
  new_b->add_string("Kyrie");
  new_b->add_string("Griffin");
  new_b->add_string("Kenneth");
  new_b->add_string("Israel");
  new_b->add_string("Javier");
  new_b->add_string("Kyler");
  new_b->add_string("Jax");
  new_b->add_string("Amari");
  new_b->add_string("Zane");
  new_b->add_string("Emilio");
  new_b->add_string("Knox");
  new_b->add_string("Adonis");
  new_b->add_string("Aidan");
  new_b->add_string("Kaden");
  new_b->add_string("Paul");
  new_b->add_string("Omar");
  new_b->add_string("Brian");
  new_b->add_string("Louis");
  new_b->add_string("Caden");
  new_b->add_string("Maximiliano");
  new_b->add_string("Holden");
  new_b->add_string("Paxton");
  new_b->add_string("Nash");
  new_b->add_string("Bradley");
  new_b->add_string("Bryan");
  new_b->add_string("Simon");
  new_b->add_string("Phoenix");
  new_b->add_string("Lane");
  new_b->add_string("Josue");
  new_b->add_string("Colin");
  new_b->add_string("Rafael");
  new_b->add_string("Kyle");
  new_b->add_string("Riley");
  new_b->add_string("Jorge");
  new_b->add_string("Beckham");
  new_b->add_string("Cayden");
  new_b->add_string("Jaden");
  new_b->add_string("Emerson");
  new_b->add_string("Ronan");
  new_b->add_string("Karson");
  new_b->add_string("Arlo");
  new_b->add_string("Tobias");
  new_b->add_string("Brady");
  new_b->add_string("Clayton");
  new_b->add_string("Francisco");
  new_b->add_string("Zander");
  new_b->add_string("Erick");
  new_b->add_string("Walter");
  new_b->add_string("Daxton");
  new_b->add_string("Cash");
  new_b->add_string("Martin");
  new_b->add_string("Damien");
  new_b->add_string("Dallas");
  new_b->add_string("Cody");
  new_b->add_string("Chance");
  new_b->add_string("Jensen");
  new_b->add_string("Finley");
  new_b->add_string("Jett");
  new_b->add_string("Corbin");
  new_b->add_string("Kash");
  new_b->add_string("Reid");
  new_b->add_string("Kameron");
  new_b->add_string("Andre");
  new_b->add_string("Gunner");
  new_b->add_string("Jake");
  new_b->add_string("Hayes");
  new_b->add_string("Manuel");
  new_b->add_string("Prince");
  new_b->add_string("Bodhi");
  new_b->add_string("Cohen");
  new_b->add_string("Sean");
  new_b->add_string("Khalil");
  new_b->add_string("Hendrix");
  new_b->add_string("Derek");
  new_b->add_string("Cristian");
  new_b->add_string("Cruz");
  new_b->add_string("Kairo");
  new_b->add_string("Dante");
  new_b->add_string("Atticus");
  new_b->add_string("Killian");
  new_b->add_string("Stephen");
  new_b->add_string("Orion");
  new_b->add_string("Malakai");
  new_b->add_string("Ali");
  new_b->add_string("Eduardo");
  new_b->add_string("Fernando");
  new_b->add_string("Anderson");
  new_b->add_string("Angelo");
  new_b->add_string("Spencer");
  new_b->add_string("Gideon");
  new_b->add_string("Mario");
  new_b->add_string("Titus");
  new_b->add_string("Travis");
  new_b->add_string("Rylan");
  new_b->add_string("Kayson");
  new_b->add_string("Ricardo");
  new_b->add_string("Tanner");
  new_b->add_string("Malcolm");
  new_b->add_string("Raymond");
  new_b->add_string("Odin");
  new_b->add_string("Cesar");
  new_b->add_string("Lennox");
  new_b->add_string("Joaquin");
  new_b->add_string("Kane");
  new_b->add_string("Wade");
  new_b->add_string("Muhammad");
  new_b->add_string("Iker");
  new_b->add_string("Jaylen");
  new_b->add_string("Crew");
  new_b->add_string("Zayn");
  new_b->add_string("Hector");
  new_b->add_string("Ellis");
  new_b->add_string("Leonel");
  new_b->add_string("Cairo");
  new_b->add_string("Garrett");
  new_b->add_string("Romeo");
  new_b->add_string("Dakota");
  new_b->add_string("Edwin");
  new_b->add_string("Warren");
  new_b->add_string("Julius");
  new_b->add_string("Major");
  new_b->add_string("Donovan");
  new_b->add_string("Caiden");
  new_b->add_string("Tyson");
  new_b->add_string("Nico");
  new_b->add_string("Sergio");
  new_b->add_string("Nasir");
  new_b->add_string("Rory");
  new_b->add_string("Devin");
  new_b->add_string("Jaiden");
  new_b->add_string("Jared");
  new_b->add_string("Kason");
  new_b->add_string("Malik");
  new_b->add_string("Jeffrey");
  new_b->add_string("Ismael");
  new_b->add_string("Elian");
  new_b->add_string("Marshall");
  new_b->add_string("Lawson");
  new_b->add_string("Desmond");
  new_b->add_string("Winston");
  new_b->add_string("Nehemiah");
  new_b->add_string("Ari");
  new_b->add_string("Conner");
  new_b->add_string("Jay");
  new_b->add_string("Kade");
  new_b->add_string("Andy");
  new_b->add_string("Johnny");
  new_b->add_string("Jayceon");
  new_b->add_string("Marco");
  new_b->add_string("Seth");
  new_b->add_string("Ibrahim");
  new_b->add_string("Raiden");
  new_b->add_string("Collin");
  new_b->add_string("Edgar");
  new_b->add_string("Erik");
  new_b->add_string("Troy");
  new_b->add_string("Clark");
  new_b->add_string("Jaxton");
  new_b->add_string("Johnathan");
  new_b->add_string("Gregory");
  new_b->add_string("Russell");
  new_b->add_string("Royce");
  new_b->add_string("Fabian");
  new_b->add_string("Ezequiel");
  new_b->add_string("Noel");
  new_b->add_string("Pablo");
  new_b->add_string("Cade");
  new_b->add_string("Pedro");
  new_b->add_string("Sullivan");
  new_b->add_string("Trevor");
  new_b->add_string("Reed");
  new_b->add_string("Quinn");
  new_b->add_string("Frank");
  new_b->add_string("Harvey");
  new_b->add_string("Princeton");
  new_b->add_string("Zayne");
  new_b->add_string("Matthias");
  new_b->add_string("Conor");
  new_b->add_string("Sterling");
  new_b->add_string("Dax");
  new_b->add_string("Grady");
  new_b->add_string("Cyrus");
  new_b->add_string("Gage");
  new_b->add_string("Leland");
  new_b->add_string("Solomon");
  new_b->add_string("Emanuel");
  new_b->add_string("Niko");
  new_b->add_string("Ruben");
  new_b->add_string("Kasen");
  new_b->add_string("Mathias");
  new_b->add_string("Kashton");
  new_b->add_string("Franklin");
  new_b->add_string("Remy");
  new_b->add_string("Shane");
  new_b->add_string("Kendrick");
  new_b->add_string("Shawn");
  new_b->add_string("Otto");
  new_b->add_string("Armani");
  new_b->add_string("Keegan");
  new_b->add_string("Finnegan");
  new_b->add_string("Memphis");
  new_b->add_string("Bowen");
  new_b->add_string("Dominick");
  new_b->add_string("Kolton");
  new_b->add_string("Jamison");
  new_b->add_string("Allen");
  new_b->add_string("Philip");
  new_b->add_string("Tate");
  new_b->add_string("Peyton");
  new_b->add_string("Jase");
  new_b->add_string("Oakley");
  new_b->add_string("Rhys");
  new_b->add_string("Kyson");
  new_b->add_string("Adan");
  new_b->add_string("Esteban");
  new_b->add_string("Dalton");
  new_b->add_string("Gianni");
  new_b->add_string("Callum");
  new_b->add_string("Sage");
  new_b->add_string("Alexis");
  new_b->add_string("Milan");
  new_b->add_string("Moises");
  new_b->add_string("Jonas");
  new_b->add_string("Uriel");
  new_b->add_string("Colson");
  new_b->add_string("Marcos");
  new_b->add_string("Zaiden");
  new_b->add_string("Hank");
  new_b->add_string("Damon");
  new_b->add_string("Hugo");
  new_b->add_string("Ronin");
  new_b->add_string("Royal");
  new_b->add_string("Kamden");
  new_b->add_string("Dexter");
  new_b->add_string("Luciano");
  new_b->add_string("Alonzo");
  new_b->add_string("Augustus");
  new_b->add_string("Kamari");
  new_b->add_string("Eden");
  new_b->add_string("Roberto");
  new_b->add_string("Baker");
  new_b->add_string("Bruce");
  new_b->add_string("Kian");
  new_b->add_string("Albert");
  new_b->add_string("Frederick");
  new_b->add_string("Mohamed");
  new_b->add_string("Abram");
  new_b->add_string("Omari");
  new_b->add_string("Porter");
  new_b->add_string("Enrique");
  new_b->add_string("Alijah");
  new_b->add_string("Francis");
  new_b->add_string("Leonidas");
  new_b->add_string("Zachariah");
  new_b->add_string("Landen");
  new_b->add_string("Wilder");
  new_b->add_string("Apollo");
  new_b->add_string("Santino");
  new_b->add_string("Tatum");
  new_b->add_string("Pierce");
  new_b->add_string("Forrest");
  new_b->add_string("Corey");
  new_b->add_string("Derrick");
  new_b->add_string("Isaias");
  new_b->add_string("Kaison");
  new_b->add_string("Kieran");
  new_b->add_string("Arjun");
  new_b->add_string("Gunnar");
  new_b->add_string("Rocco");
  new_b->add_string("Emmitt");
  std::cout << "filter print: " << new_b->expose_filter() << "\n";
  std::cout << "filter lookup: " << "Liam " << new_b->lookup("Liam") << "\n";
  std::cout << "filter lookup: " << "Noah " << new_b->lookup("Noah") << "\n";
  std::cout << "filter lookup: " << "Oliver " << new_b->lookup("Oliver") << "\n";
  std::cout << "filter lookup: " << "William " << new_b->lookup("William") << "\n";
  std::cout << "filter lookup: " << "Elijah " << new_b->lookup("Elijah") << "\n";
  std::cout << "filter lookup: " << "James " << new_b->lookup("James") << "\n";
  std::cout << "filter lookup: " << "Benjamin " << new_b->lookup("Benjamin") << "\n";
  std::cout << "filter lookup: " << "Lucas " << new_b->lookup("Lucas") << "\n";
  std::cout << "filter lookup: " << "Mason " << new_b->lookup("Mason") << "\n";
  std::cout << "filter lookup: " << "Ethan " << new_b->lookup("Ethan") << "\n";
  std::cout << "filter lookup: " << "Alexander " << new_b->lookup("Alexander") << "\n";
  std::cout << "filter lookup: " << "Henry " << new_b->lookup("Henry") << "\n";
  std::cout << "filter lookup: " << "Jacob " << new_b->lookup("Jacob") << "\n";
  std::cout << "filter lookup: " << "Michael " << new_b->lookup("Michael") << "\n";
  std::cout << "filter lookup: " << "Daniel " << new_b->lookup("Daniel") << "\n";
  std::cout << "filter lookup: " << "Logan " << new_b->lookup("Logan") << "\n";
  std::cout << "filter lookup: " << "Jackson " << new_b->lookup("Jackson") << "\n";
  std::cout << "filter lookup: " << "Sebastian " << new_b->lookup("Sebastian") << "\n";
  std::cout << "filter lookup: " << "Jack " << new_b->lookup("Jack") << "\n";
  std::cout << "filter lookup: " << "Aiden " << new_b->lookup("Aiden") << "\n";
  std::cout << "filter lookup: " << "Owen " << new_b->lookup("Owen") << "\n";
  std::cout << "filter lookup: " << "Samuel " << new_b->lookup("Samuel") << "\n";
  std::cout << "filter lookup: " << "Matthew " << new_b->lookup("Matthew") << "\n";
  std::cout << "filter lookup: " << "Joseph " << new_b->lookup("Joseph") << "\n";
  std::cout << "filter lookup: " << "Levi " << new_b->lookup("Levi") << "\n";
  std::cout << "filter lookup: " << "Mateo " << new_b->lookup("Mateo") << "\n";
  std::cout << "filter lookup: " << "David " << new_b->lookup("David") << "\n";
  std::cout << "filter lookup: " << "John " << new_b->lookup("John") << "\n";
  std::cout << "filter lookup: " << "Wyatt " << new_b->lookup("Wyatt") << "\n";
  std::cout << "filter lookup: " << "Carter " << new_b->lookup("Carter") << "\n";
  std::cout << "filter lookup: " << "Julian " << new_b->lookup("Julian") << "\n";
  std::cout << "filter lookup: " << "Luke " << new_b->lookup("Luke") << "\n";
  std::cout << "filter lookup: " << "Grayson " << new_b->lookup("Grayson") << "\n";
  std::cout << "filter lookup: " << "Isaac " << new_b->lookup("Isaac") << "\n";
  std::cout << "filter lookup: " << "Jayden " << new_b->lookup("Jayden") << "\n";
  std::cout << "filter lookup: " << "Theodore " << new_b->lookup("Theodore") << "\n";
  std::cout << "filter lookup: " << "Gabriel " << new_b->lookup("Gabriel") << "\n";
  std::cout << "filter lookup: " << "Anthony " << new_b->lookup("Anthony") << "\n";
  std::cout << "filter lookup: " << "Dylan " << new_b->lookup("Dylan") << "\n";
  std::cout << "filter lookup: " << "Leo " << new_b->lookup("Leo") << "\n";
  std::cout << "filter lookup: " << "Lincoln " << new_b->lookup("Lincoln") << "\n";
  std::cout << "filter lookup: " << "Jaxon " << new_b->lookup("Jaxon") << "\n";
  std::cout << "filter lookup: " << "Asher " << new_b->lookup("Asher") << "\n";
  std::cout << "filter lookup: " << "Christopher " << new_b->lookup("Christopher") << "\n";
  std::cout << "filter lookup: " << "Josiah " << new_b->lookup("Josiah") << "\n";
  std::cout << "filter lookup: " << "Andrew " << new_b->lookup("Andrew") << "\n";
  std::cout << "filter lookup: " << "Thomas " << new_b->lookup("Thomas") << "\n";
  std::cout << "filter lookup: " << "Joshua " << new_b->lookup("Joshua") << "\n";
  std::cout << "filter lookup: " << "Ezra " << new_b->lookup("Ezra") << "\n";
  std::cout << "filter lookup: " << "Hudson " << new_b->lookup("Hudson") << "\n";
  std::cout << "filter lookup: " << "Charles " << new_b->lookup("Charles") << "\n";
  std::cout << "filter lookup: " << "Caleb " << new_b->lookup("Caleb") << "\n";
  std::cout << "filter lookup: " << "Isaiah " << new_b->lookup("Isaiah") << "\n";
  std::cout << "filter lookup: " << "Ryan " << new_b->lookup("Ryan") << "\n";
  std::cout << "filter lookup: " << "Nathan " << new_b->lookup("Nathan") << "\n";
  std::cout << "filter lookup: " << "Adrian " << new_b->lookup("Adrian") << "\n";
  std::cout << "filter lookup: " << "Christian " << new_b->lookup("Christian") << "\n";
  std::cout << "filter lookup: " << "Maverick " << new_b->lookup("Maverick") << "\n";
  std::cout << "filter lookup: " << "Colton " << new_b->lookup("Colton") << "\n";
  std::cout << "filter lookup: " << "Elias " << new_b->lookup("Elias") << "\n";
  std::cout << "filter lookup: " << "Aaron " << new_b->lookup("Aaron") << "\n";
  std::cout << "filter lookup: " << "Eli " << new_b->lookup("Eli") << "\n";
  std::cout << "filter lookup: " << "Landon " << new_b->lookup("Landon") << "\n";
  std::cout << "filter lookup: " << "Jonathan " << new_b->lookup("Jonathan") << "\n";
  std::cout << "filter lookup: " << "Nolan " << new_b->lookup("Nolan") << "\n";
  std::cout << "filter lookup: " << "Hunter " << new_b->lookup("Hunter") << "\n";
  std::cout << "filter lookup: " << "Cameron " << new_b->lookup("Cameron") << "\n";
  std::cout << "filter lookup: " << "Connor " << new_b->lookup("Connor") << "\n";
  std::cout << "filter lookup: " << "Santiago " << new_b->lookup("Santiago") << "\n";
  std::cout << "filter lookup: " << "Jeremiah " << new_b->lookup("Jeremiah") << "\n";
  std::cout << "filter lookup: " << "Ezekiel " << new_b->lookup("Ezekiel") << "\n";
  std::cout << "filter lookup: " << "Angel " << new_b->lookup("Angel") << "\n";
  std::cout << "filter lookup: " << "Roman " << new_b->lookup("Roman") << "\n";
  std::cout << "filter lookup: " << "Easton " << new_b->lookup("Easton") << "\n";
  std::cout << "filter lookup: " << "Miles " << new_b->lookup("Miles") << "\n";
  std::cout << "filter lookup: " << "Robert " << new_b->lookup("Robert") << "\n";
  std::cout << "filter lookup: " << "Jameson " << new_b->lookup("Jameson") << "\n";
  std::cout << "filter lookup: " << "Nicholas " << new_b->lookup("Nicholas") << "\n";
  std::cout << "filter lookup: " << "Greyson " << new_b->lookup("Greyson") << "\n";
  std::cout << "filter lookup: " << "Cooper " << new_b->lookup("Cooper") << "\n";
  std::cout << "filter lookup: " << "Ian " << new_b->lookup("Ian") << "\n";
  std::cout << "filter lookup: " << "Carson " << new_b->lookup("Carson") << "\n";
  std::cout << "filter lookup: " << "Axel " << new_b->lookup("Axel") << "\n";
  std::cout << "filter lookup: " << "Jaxson " << new_b->lookup("Jaxson") << "\n";
  std::cout << "filter lookup: " << "Dominic " << new_b->lookup("Dominic") << "\n";
  std::cout << "filter lookup: " << "Leonardo " << new_b->lookup("Leonardo") << "\n";
  std::cout << "filter lookup: " << "Luca " << new_b->lookup("Luca") << "\n";
  std::cout << "filter lookup: " << "Austin " << new_b->lookup("Austin") << "\n";
  std::cout << "filter lookup: " << "Jordan " << new_b->lookup("Jordan") << "\n";
  std::cout << "filter lookup: " << "Adam " << new_b->lookup("Adam") << "\n";
  std::cout << "filter lookup: " << "Xavier " << new_b->lookup("Xavier") << "\n";
  std::cout << "filter lookup: " << "Jose " << new_b->lookup("Jose") << "\n";
  std::cout << "filter lookup: " << "Jace " << new_b->lookup("Jace") << "\n";
  std::cout << "filter lookup: " << "Everett " << new_b->lookup("Everett") << "\n";
  std::cout << "filter lookup: " << "Declan " << new_b->lookup("Declan") << "\n";
  std::cout << "filter lookup: " << "Evan " << new_b->lookup("Evan") << "\n";
  std::cout << "filter lookup: " << "Kayden " << new_b->lookup("Kayden") << "\n";
  std::cout << "filter lookup: " << "Parker " << new_b->lookup("Parker") << "\n";
  std::cout << "filter lookup: " << "Wesley " << new_b->lookup("Wesley") << "\n";
  std::cout << "filter lookup: " << "Kai " << new_b->lookup("Kai") << "\n";
  std::cout << "filter lookup: " << "Brayden " << new_b->lookup("Brayden") << "\n";
  std::cout << "filter lookup: " << "Bryson " << new_b->lookup("Bryson") << "\n";
  std::cout << "filter lookup: " << "Weston " << new_b->lookup("Weston") << "\n";
  std::cout << "filter lookup: " << "Jason " << new_b->lookup("Jason") << "\n";
  std::cout << "filter lookup: " << "Emmett " << new_b->lookup("Emmett") << "\n";
  std::cout << "filter lookup: " << "Sawyer " << new_b->lookup("Sawyer") << "\n";
  std::cout << "filter lookup: " << "Silas " << new_b->lookup("Silas") << "\n";
  std::cout << "filter lookup: " << "Bennett " << new_b->lookup("Bennett") << "\n";
  std::cout << "filter lookup: " << "Brooks " << new_b->lookup("Brooks") << "\n";
  std::cout << "filter lookup: " << "Micah " << new_b->lookup("Micah") << "\n";
  std::cout << "filter lookup: " << "Damian " << new_b->lookup("Damian") << "\n";
  std::cout << "filter lookup: " << "Harrison " << new_b->lookup("Harrison") << "\n";
  std::cout << "filter lookup: " << "Waylon " << new_b->lookup("Waylon") << "\n";
  std::cout << "filter lookup: " << "Ayden " << new_b->lookup("Ayden") << "\n";
  std::cout << "filter lookup: " << "Vincent " << new_b->lookup("Vincent") << "\n";
  std::cout << "filter lookup: " << "Ryder " << new_b->lookup("Ryder") << "\n";
  std::cout << "filter lookup: " << "Kingston " << new_b->lookup("Kingston") << "\n";
  std::cout << "filter lookup: " << "Rowan " << new_b->lookup("Rowan") << "\n";
  std::cout << "filter lookup: " << "George " << new_b->lookup("George") << "\n";
  std::cout << "filter lookup: " << "Luis " << new_b->lookup("Luis") << "\n";
  std::cout << "filter lookup: " << "Chase " << new_b->lookup("Chase") << "\n";
  std::cout << "filter lookup: " << "Cole " << new_b->lookup("Cole") << "\n";
  std::cout << "filter lookup: " << "Nathaniel " << new_b->lookup("Nathaniel") << "\n";
  std::cout << "filter lookup: " << "Zachary " << new_b->lookup("Zachary") << "\n";
  std::cout << "filter lookup: " << "Ashton " << new_b->lookup("Ashton") << "\n";
  std::cout << "filter lookup: " << "Braxton " << new_b->lookup("Braxton") << "\n";
  std::cout << "filter lookup: " << "Gavin " << new_b->lookup("Gavin") << "\n";
  std::cout << "filter lookup: " << "Tyler " << new_b->lookup("Tyler") << "\n";
  std::cout << "filter lookup: " << "Diego " << new_b->lookup("Diego") << "\n";
  std::cout << "filter lookup: " << "Bentley " << new_b->lookup("Bentley") << "\n";
  std::cout << "filter lookup: " << "Amir " << new_b->lookup("Amir") << "\n";
  std::cout << "filter lookup: " << "Beau " << new_b->lookup("Beau") << "\n";
  std::cout << "filter lookup: " << "Gael " << new_b->lookup("Gael") << "\n";
  std::cout << "filter lookup: " << "Carlos " << new_b->lookup("Carlos") << "\n";
  std::cout << "filter lookup: " << "Ryker " << new_b->lookup("Ryker") << "\n";
  std::cout << "filter lookup: " << "Jasper " << new_b->lookup("Jasper") << "\n";
  std::cout << "filter lookup: " << "Max " << new_b->lookup("Max") << "\n";
  std::cout << "filter lookup: " << "Juan " << new_b->lookup("Juan") << "\n";
  std::cout << "filter lookup: " << "Ivan " << new_b->lookup("Ivan") << "\n";
  std::cout << "filter lookup: " << "Brandon " << new_b->lookup("Brandon") << "\n";
  std::cout << "filter lookup: " << "Jonah " << new_b->lookup("Jonah") << "\n";
  std::cout << "filter lookup: " << "Giovanni " << new_b->lookup("Giovanni") << "\n";
  std::cout << "filter lookup: " << "Kaiden " << new_b->lookup("Kaiden") << "\n";
  std::cout << "filter lookup: " << "Myles " << new_b->lookup("Myles") << "\n";
  std::cout << "filter lookup: " << "Calvin " << new_b->lookup("Calvin") << "\n";
  std::cout << "filter lookup: " << "Lorenzo " << new_b->lookup("Lorenzo") << "\n";
  std::cout << "filter lookup: " << "Maxwell " << new_b->lookup("Maxwell") << "\n";
  std::cout << "filter lookup: " << "Jayce " << new_b->lookup("Jayce") << "\n";
  std::cout << "filter lookup: " << "Kevin " << new_b->lookup("Kevin") << "\n";
  std::cout << "filter lookup: " << "Legend " << new_b->lookup("Legend") << "\n";
  std::cout << "filter lookup: " << "Tristan " << new_b->lookup("Tristan") << "\n";
  std::cout << "filter lookup: " << "Jesus " << new_b->lookup("Jesus") << "\n";
  std::cout << "filter lookup: " << "Jude " << new_b->lookup("Jude") << "\n";
  std::cout << "filter lookup: " << "Zion " << new_b->lookup("Zion") << "\n";
  std::cout << "filter lookup: " << "Justin " << new_b->lookup("Justin") << "\n";
  std::cout << "filter lookup: " << "Maddox " << new_b->lookup("Maddox") << "\n";
  std::cout << "filter lookup: " << "Abel " << new_b->lookup("Abel") << "\n";
  std::cout << "filter lookup: " << "King " << new_b->lookup("King") << "\n";
  std::cout << "filter lookup: " << "Camden " << new_b->lookup("Camden") << "\n";
  std::cout << "filter lookup: " << "Elliott " << new_b->lookup("Elliott") << "\n";
  std::cout << "filter lookup: " << "Malachi " << new_b->lookup("Malachi") << "\n";
  std::cout << "filter lookup: " << "Milo " << new_b->lookup("Milo") << "\n";
  std::cout << "filter lookup: " << "Emmanuel " << new_b->lookup("Emmanuel") << "\n";
  std::cout << "filter lookup: " << "Karter " << new_b->lookup("Karter") << "\n";
  std::cout << "filter lookup: " << "Rhett " << new_b->lookup("Rhett") << "\n";
  std::cout << "filter lookup: " << "Alex " << new_b->lookup("Alex") << "\n";
  std::cout << "filter lookup: " << "August " << new_b->lookup("August") << "\n";
  std::cout << "filter lookup: " << "River " << new_b->lookup("River") << "\n";
  std::cout << "filter lookup: " << "Xander " << new_b->lookup("Xander") << "\n";
  std::cout << "filter lookup: " << "Antonio " << new_b->lookup("Antonio") << "\n";
  std::cout << "filter lookup: " << "Brody " << new_b->lookup("Brody") << "\n";
  std::cout << "filter lookup: " << "Finn " << new_b->lookup("Finn") << "\n";
  std::cout << "filter lookup: " << "Elliot " << new_b->lookup("Elliot") << "\n";
  std::cout << "filter lookup: " << "Dean " << new_b->lookup("Dean") << "\n";
  std::cout << "filter lookup: " << "Emiliano " << new_b->lookup("Emiliano") << "\n";
  std::cout << "filter lookup: " << "Eric " << new_b->lookup("Eric") << "\n";
  std::cout << "filter lookup: " << "Miguel " << new_b->lookup("Miguel") << "\n";
  std::cout << "filter lookup: " << "Arthur " << new_b->lookup("Arthur") << "\n";
  std::cout << "filter lookup: " << "Matteo " << new_b->lookup("Matteo") << "\n";
  std::cout << "filter lookup: " << "Graham " << new_b->lookup("Graham") << "\n";
  std::cout << "filter lookup: " << "Alan " << new_b->lookup("Alan") << "\n";
  std::cout << "filter lookup: " << "Nicolas " << new_b->lookup("Nicolas") << "\n";
  std::cout << "filter lookup: " << "Blake " << new_b->lookup("Blake") << "\n";
  std::cout << "filter lookup: " << "Thiago " << new_b->lookup("Thiago") << "\n";
  std::cout << "filter lookup: " << "Adriel " << new_b->lookup("Adriel") << "\n";
  std::cout << "filter lookup: " << "Victor " << new_b->lookup("Victor") << "\n";
  std::cout << "filter lookup: " << "Joel " << new_b->lookup("Joel") << "\n";
  std::cout << "filter lookup: " << "Timothy " << new_b->lookup("Timothy") << "\n";
  std::cout << "filter lookup: " << "Hayden " << new_b->lookup("Hayden") << "\n";
  std::cout << "filter lookup: " << "Judah " << new_b->lookup("Judah") << "\n";
  std::cout << "filter lookup: " << "Abraham " << new_b->lookup("Abraham") << "\n";
  std::cout << "filter lookup: " << "Edward " << new_b->lookup("Edward") << "\n";
  std::cout << "filter lookup: " << "Messiah " << new_b->lookup("Messiah") << "\n";
  std::cout << "filter lookup: " << "Zayden " << new_b->lookup("Zayden") << "\n";
  std::cout << "filter lookup: " << "Theo " << new_b->lookup("Theo") << "\n";
  std::cout << "filter lookup: " << "Tucker " << new_b->lookup("Tucker") << "\n";
  std::cout << "filter lookup: " << "Grant " << new_b->lookup("Grant") << "\n";
  std::cout << "filter lookup: " << "Richard " << new_b->lookup("Richard") << "\n";
  std::cout << "filter lookup: " << "Alejandro " << new_b->lookup("Alejandro") << "\n";
  std::cout << "filter lookup: " << "Steven " << new_b->lookup("Steven") << "\n";
  std::cout << "filter lookup: " << "Jesse " << new_b->lookup("Jesse") << "\n";
  std::cout << "filter lookup: " << "Dawson " << new_b->lookup("Dawson") << "\n";
  std::cout << "filter lookup: " << "Bryce " << new_b->lookup("Bryce") << "\n";
  std::cout << "filter lookup: " << "Avery " << new_b->lookup("Avery") << "\n";
  std::cout << "filter lookup: " << "Oscar " << new_b->lookup("Oscar") << "\n";
  std::cout << "filter lookup: " << "Patrick " << new_b->lookup("Patrick") << "\n";
  std::cout << "filter lookup: " << "Archer " << new_b->lookup("Archer") << "\n";
  std::cout << "filter lookup: " << "Barrett " << new_b->lookup("Barrett") << "\n";
  std::cout << "filter lookup: " << "Leon " << new_b->lookup("Leon") << "\n";
  std::cout << "filter lookup: " << "Colt " << new_b->lookup("Colt") << "\n";
  std::cout << "filter lookup: " << "Charlie " << new_b->lookup("Charlie") << "\n";
  std::cout << "filter lookup: " << "Peter " << new_b->lookup("Peter") << "\n";
  std::cout << "filter lookup: " << "Kaleb " << new_b->lookup("Kaleb") << "\n";
  std::cout << "filter lookup: " << "Lukas " << new_b->lookup("Lukas") << "\n";
  std::cout << "filter lookup: " << "Beckett " << new_b->lookup("Beckett") << "\n";
  std::cout << "filter lookup: " << "Jeremy " << new_b->lookup("Jeremy") << "\n";
  std::cout << "filter lookup: " << "Preston " << new_b->lookup("Preston") << "\n";
  std::cout << "filter lookup: " << "Enzo " << new_b->lookup("Enzo") << "\n";
  std::cout << "filter lookup: " << "Luka " << new_b->lookup("Luka") << "\n";
  std::cout << "filter lookup: " << "Andres " << new_b->lookup("Andres") << "\n";
  std::cout << "filter lookup: " << "Marcus " << new_b->lookup("Marcus") << "\n";
  std::cout << "filter lookup: " << "Felix " << new_b->lookup("Felix") << "\n";
  std::cout << "filter lookup: " << "Mark " << new_b->lookup("Mark") << "\n";
  std::cout << "filter lookup: " << "Ace " << new_b->lookup("Ace") << "\n";
  std::cout << "filter lookup: " << "Brantley " << new_b->lookup("Brantley") << "\n";
  std::cout << "filter lookup: " << "Atlas " << new_b->lookup("Atlas") << "\n";
  std::cout << "filter lookup: " << "Remington " << new_b->lookup("Remington") << "\n";
  std::cout << "filter lookup: " << "Maximus " << new_b->lookup("Maximus") << "\n";
  std::cout << "filter lookup: " << "Matias " << new_b->lookup("Matias") << "\n";
  std::cout << "filter lookup: " << "Walker " << new_b->lookup("Walker") << "\n";
  std::cout << "filter lookup: " << "Kyrie " << new_b->lookup("Kyrie") << "\n";
  std::cout << "filter lookup: " << "Griffin " << new_b->lookup("Griffin") << "\n";
  std::cout << "filter lookup: " << "Kenneth " << new_b->lookup("Kenneth") << "\n";
  std::cout << "filter lookup: " << "Israel " << new_b->lookup("Israel") << "\n";
  std::cout << "filter lookup: " << "Javier " << new_b->lookup("Javier") << "\n";
  std::cout << "filter lookup: " << "Kyler " << new_b->lookup("Kyler") << "\n";
  std::cout << "filter lookup: " << "Jax " << new_b->lookup("Jax") << "\n";
  std::cout << "filter lookup: " << "Amari " << new_b->lookup("Amari") << "\n";
  std::cout << "filter lookup: " << "Zane " << new_b->lookup("Zane") << "\n";
  std::cout << "filter lookup: " << "Emilio " << new_b->lookup("Emilio") << "\n";
  std::cout << "filter lookup: " << "Knox " << new_b->lookup("Knox") << "\n";
  std::cout << "filter lookup: " << "Adonis " << new_b->lookup("Adonis") << "\n";
  std::cout << "filter lookup: " << "Aidan " << new_b->lookup("Aidan") << "\n";
  std::cout << "filter lookup: " << "Kaden " << new_b->lookup("Kaden") << "\n";
  std::cout << "filter lookup: " << "Paul " << new_b->lookup("Paul") << "\n";
  std::cout << "filter lookup: " << "Omar " << new_b->lookup("Omar") << "\n";
  std::cout << "filter lookup: " << "Brian " << new_b->lookup("Brian") << "\n";
  std::cout << "filter lookup: " << "Louis " << new_b->lookup("Louis") << "\n";
  std::cout << "filter lookup: " << "Caden " << new_b->lookup("Caden") << "\n";
  std::cout << "filter lookup: " << "Maximiliano " << new_b->lookup("Maximiliano") << "\n";
  std::cout << "filter lookup: " << "Holden " << new_b->lookup("Holden") << "\n";
  std::cout << "filter lookup: " << "Paxton " << new_b->lookup("Paxton") << "\n";
  std::cout << "filter lookup: " << "Nash " << new_b->lookup("Nash") << "\n";
  std::cout << "filter lookup: " << "Bradley " << new_b->lookup("Bradley") << "\n";
  std::cout << "filter lookup: " << "Bryan " << new_b->lookup("Bryan") << "\n";
  std::cout << "filter lookup: " << "Simon " << new_b->lookup("Simon") << "\n";
  std::cout << "filter lookup: " << "Phoenix " << new_b->lookup("Phoenix") << "\n";
  std::cout << "filter lookup: " << "Lane " << new_b->lookup("Lane") << "\n";
  std::cout << "filter lookup: " << "Josue " << new_b->lookup("Josue") << "\n";
  std::cout << "filter lookup: " << "Colin " << new_b->lookup("Colin") << "\n";
  std::cout << "filter lookup: " << "Rafael " << new_b->lookup("Rafael") << "\n";
  std::cout << "filter lookup: " << "Kyle " << new_b->lookup("Kyle") << "\n";
  std::cout << "filter lookup: " << "Riley " << new_b->lookup("Riley") << "\n";
  std::cout << "filter lookup: " << "Jorge " << new_b->lookup("Jorge") << "\n";
  std::cout << "filter lookup: " << "Beckham " << new_b->lookup("Beckham") << "\n";
  std::cout << "filter lookup: " << "Cayden " << new_b->lookup("Cayden") << "\n";
  std::cout << "filter lookup: " << "Jaden " << new_b->lookup("Jaden") << "\n";
  std::cout << "filter lookup: " << "Emerson " << new_b->lookup("Emerson") << "\n";
  std::cout << "filter lookup: " << "Ronan " << new_b->lookup("Ronan") << "\n";
  std::cout << "filter lookup: " << "Karson " << new_b->lookup("Karson") << "\n";
  std::cout << "filter lookup: " << "Arlo " << new_b->lookup("Arlo") << "\n";
  std::cout << "filter lookup: " << "Tobias " << new_b->lookup("Tobias") << "\n";
  std::cout << "filter lookup: " << "Brady " << new_b->lookup("Brady") << "\n";
  std::cout << "filter lookup: " << "Clayton " << new_b->lookup("Clayton") << "\n";
  std::cout << "filter lookup: " << "Francisco " << new_b->lookup("Francisco") << "\n";
  std::cout << "filter lookup: " << "Zander " << new_b->lookup("Zander") << "\n";
  std::cout << "filter lookup: " << "Erick " << new_b->lookup("Erick") << "\n";
  std::cout << "filter lookup: " << "Walter " << new_b->lookup("Walter") << "\n";
  std::cout << "filter lookup: " << "Daxton " << new_b->lookup("Daxton") << "\n";
  std::cout << "filter lookup: " << "Cash " << new_b->lookup("Cash") << "\n";
  std::cout << "filter lookup: " << "Martin " << new_b->lookup("Martin") << "\n";
  std::cout << "filter lookup: " << "Damien " << new_b->lookup("Damien") << "\n";
  std::cout << "filter lookup: " << "Dallas " << new_b->lookup("Dallas") << "\n";
  std::cout << "filter lookup: " << "Cody " << new_b->lookup("Cody") << "\n";
  std::cout << "filter lookup: " << "Chance " << new_b->lookup("Chance") << "\n";
  std::cout << "filter lookup: " << "Jensen " << new_b->lookup("Jensen") << "\n";
  std::cout << "filter lookup: " << "Finley " << new_b->lookup("Finley") << "\n";
  std::cout << "filter lookup: " << "Jett " << new_b->lookup("Jett") << "\n";
  std::cout << "filter lookup: " << "Corbin " << new_b->lookup("Corbin") << "\n";
  std::cout << "filter lookup: " << "Kash " << new_b->lookup("Kash") << "\n";
  std::cout << "filter lookup: " << "Reid " << new_b->lookup("Reid") << "\n";
  std::cout << "filter lookup: " << "Kameron " << new_b->lookup("Kameron") << "\n";
  std::cout << "filter lookup: " << "Andre " << new_b->lookup("Andre") << "\n";
  std::cout << "filter lookup: " << "Gunner " << new_b->lookup("Gunner") << "\n";
  std::cout << "filter lookup: " << "Jake " << new_b->lookup("Jake") << "\n";
  std::cout << "filter lookup: " << "Hayes " << new_b->lookup("Hayes") << "\n";
  std::cout << "filter lookup: " << "Manuel " << new_b->lookup("Manuel") << "\n";
  std::cout << "filter lookup: " << "Prince " << new_b->lookup("Prince") << "\n";
  std::cout << "filter lookup: " << "Bodhi " << new_b->lookup("Bodhi") << "\n";
  std::cout << "filter lookup: " << "Cohen " << new_b->lookup("Cohen") << "\n";
  std::cout << "filter lookup: " << "Sean " << new_b->lookup("Sean") << "\n";
  std::cout << "filter lookup: " << "Khalil " << new_b->lookup("Khalil") << "\n";
  std::cout << "filter lookup: " << "Hendrix " << new_b->lookup("Hendrix") << "\n";
  std::cout << "filter lookup: " << "Derek " << new_b->lookup("Derek") << "\n";
  std::cout << "filter lookup: " << "Cristian " << new_b->lookup("Cristian") << "\n";
  std::cout << "filter lookup: " << "Cruz " << new_b->lookup("Cruz") << "\n";
  std::cout << "filter lookup: " << "Kairo " << new_b->lookup("Kairo") << "\n";
  std::cout << "filter lookup: " << "Dante " << new_b->lookup("Dante") << "\n";
  std::cout << "filter lookup: " << "Atticus " << new_b->lookup("Atticus") << "\n";
  std::cout << "filter lookup: " << "Killian " << new_b->lookup("Killian") << "\n";
  std::cout << "filter lookup: " << "Stephen " << new_b->lookup("Stephen") << "\n";
  std::cout << "filter lookup: " << "Orion " << new_b->lookup("Orion") << "\n";
  std::cout << "filter lookup: " << "Malakai " << new_b->lookup("Malakai") << "\n";
  std::cout << "filter lookup: " << "Ali " << new_b->lookup("Ali") << "\n";
  std::cout << "filter lookup: " << "Eduardo " << new_b->lookup("Eduardo") << "\n";
  std::cout << "filter lookup: " << "Fernando " << new_b->lookup("Fernando") << "\n";
  std::cout << "filter lookup: " << "Anderson " << new_b->lookup("Anderson") << "\n";
  std::cout << "filter lookup: " << "Angelo " << new_b->lookup("Angelo") << "\n";
  std::cout << "filter lookup: " << "Spencer " << new_b->lookup("Spencer") << "\n";
  std::cout << "filter lookup: " << "Gideon " << new_b->lookup("Gideon") << "\n";
  std::cout << "filter lookup: " << "Mario " << new_b->lookup("Mario") << "\n";
  std::cout << "filter lookup: " << "Titus " << new_b->lookup("Titus") << "\n";
  std::cout << "filter lookup: " << "Travis " << new_b->lookup("Travis") << "\n";
  std::cout << "filter lookup: " << "Rylan " << new_b->lookup("Rylan") << "\n";
  std::cout << "filter lookup: " << "Kayson " << new_b->lookup("Kayson") << "\n";
  std::cout << "filter lookup: " << "Ricardo " << new_b->lookup("Ricardo") << "\n";
  std::cout << "filter lookup: " << "Tanner " << new_b->lookup("Tanner") << "\n";
  std::cout << "filter lookup: " << "Malcolm " << new_b->lookup("Malcolm") << "\n";
  std::cout << "filter lookup: " << "Raymond " << new_b->lookup("Raymond") << "\n";
  std::cout << "filter lookup: " << "Odin " << new_b->lookup("Odin") << "\n";
  std::cout << "filter lookup: " << "Cesar " << new_b->lookup("Cesar") << "\n";
  std::cout << "filter lookup: " << "Lennox " << new_b->lookup("Lennox") << "\n";
  std::cout << "filter lookup: " << "Joaquin " << new_b->lookup("Joaquin") << "\n";
  std::cout << "filter lookup: " << "Kane " << new_b->lookup("Kane") << "\n";
  std::cout << "filter lookup: " << "Wade " << new_b->lookup("Wade") << "\n";
  std::cout << "filter lookup: " << "Muhammad " << new_b->lookup("Muhammad") << "\n";
  std::cout << "filter lookup: " << "Iker " << new_b->lookup("Iker") << "\n";
  std::cout << "filter lookup: " << "Jaylen " << new_b->lookup("Jaylen") << "\n";
  std::cout << "filter lookup: " << "Crew " << new_b->lookup("Crew") << "\n";
  std::cout << "filter lookup: " << "Zayn " << new_b->lookup("Zayn") << "\n";
  std::cout << "filter lookup: " << "Hector " << new_b->lookup("Hector") << "\n";
  std::cout << "filter lookup: " << "Ellis " << new_b->lookup("Ellis") << "\n";
  std::cout << "filter lookup: " << "Leonel " << new_b->lookup("Leonel") << "\n";
  std::cout << "filter lookup: " << "Cairo " << new_b->lookup("Cairo") << "\n";
  std::cout << "filter lookup: " << "Garrett " << new_b->lookup("Garrett") << "\n";
  std::cout << "filter lookup: " << "Romeo " << new_b->lookup("Romeo") << "\n";
  std::cout << "filter lookup: " << "Dakota " << new_b->lookup("Dakota") << "\n";
  std::cout << "filter lookup: " << "Edwin " << new_b->lookup("Edwin") << "\n";
  std::cout << "filter lookup: " << "Warren " << new_b->lookup("Warren") << "\n";
  std::cout << "filter lookup: " << "Julius " << new_b->lookup("Julius") << "\n";
  std::cout << "filter lookup: " << "Major " << new_b->lookup("Major") << "\n";
  std::cout << "filter lookup: " << "Donovan " << new_b->lookup("Donovan") << "\n";
  std::cout << "filter lookup: " << "Caiden " << new_b->lookup("Caiden") << "\n";
  std::cout << "filter lookup: " << "Tyson " << new_b->lookup("Tyson") << "\n";
  std::cout << "filter lookup: " << "Nico " << new_b->lookup("Nico") << "\n";
  std::cout << "filter lookup: " << "Sergio " << new_b->lookup("Sergio") << "\n";
  std::cout << "filter lookup: " << "Nasir " << new_b->lookup("Nasir") << "\n";
  std::cout << "filter lookup: " << "Rory " << new_b->lookup("Rory") << "\n";
  std::cout << "filter lookup: " << "Devin " << new_b->lookup("Devin") << "\n";
  std::cout << "filter lookup: " << "Jaiden " << new_b->lookup("Jaiden") << "\n";
  std::cout << "filter lookup: " << "Jared " << new_b->lookup("Jared") << "\n";
  std::cout << "filter lookup: " << "Kason " << new_b->lookup("Kason") << "\n";
  std::cout << "filter lookup: " << "Malik " << new_b->lookup("Malik") << "\n";
  std::cout << "filter lookup: " << "Jeffrey " << new_b->lookup("Jeffrey") << "\n";
  std::cout << "filter lookup: " << "Ismael " << new_b->lookup("Ismael") << "\n";
  std::cout << "filter lookup: " << "Elian " << new_b->lookup("Elian") << "\n";
  std::cout << "filter lookup: " << "Marshall " << new_b->lookup("Marshall") << "\n";
  std::cout << "filter lookup: " << "Lawson " << new_b->lookup("Lawson") << "\n";
  std::cout << "filter lookup: " << "Desmond " << new_b->lookup("Desmond") << "\n";
  std::cout << "filter lookup: " << "Winston " << new_b->lookup("Winston") << "\n";
  std::cout << "filter lookup: " << "Nehemiah " << new_b->lookup("Nehemiah") << "\n";
  std::cout << "filter lookup: " << "Ari " << new_b->lookup("Ari") << "\n";
  std::cout << "filter lookup: " << "Conner " << new_b->lookup("Conner") << "\n";
  std::cout << "filter lookup: " << "Jay " << new_b->lookup("Jay") << "\n";
  std::cout << "filter lookup: " << "Kade " << new_b->lookup("Kade") << "\n";
  std::cout << "filter lookup: " << "Andy " << new_b->lookup("Andy") << "\n";
  std::cout << "filter lookup: " << "Johnny " << new_b->lookup("Johnny") << "\n";
  std::cout << "filter lookup: " << "Jayceon " << new_b->lookup("Jayceon") << "\n";
  std::cout << "filter lookup: " << "Marco " << new_b->lookup("Marco") << "\n";
  std::cout << "filter lookup: " << "Seth " << new_b->lookup("Seth") << "\n";
  std::cout << "filter lookup: " << "Ibrahim " << new_b->lookup("Ibrahim") << "\n";
  std::cout << "filter lookup: " << "Raiden " << new_b->lookup("Raiden") << "\n";
  std::cout << "filter lookup: " << "Collin " << new_b->lookup("Collin") << "\n";
  std::cout << "filter lookup: " << "Edgar " << new_b->lookup("Edgar") << "\n";
  std::cout << "filter lookup: " << "Erik " << new_b->lookup("Erik") << "\n";
  std::cout << "filter lookup: " << "Troy " << new_b->lookup("Troy") << "\n";
  std::cout << "filter lookup: " << "Clark " << new_b->lookup("Clark") << "\n";
  std::cout << "filter lookup: " << "Jaxton " << new_b->lookup("Jaxton") << "\n";
  std::cout << "filter lookup: " << "Johnathan " << new_b->lookup("Johnathan") << "\n";
  std::cout << "filter lookup: " << "Gregory " << new_b->lookup("Gregory") << "\n";
  std::cout << "filter lookup: " << "Russell " << new_b->lookup("Russell") << "\n";
  std::cout << "filter lookup: " << "Royce " << new_b->lookup("Royce") << "\n";
  std::cout << "filter lookup: " << "Fabian " << new_b->lookup("Fabian") << "\n";
  std::cout << "filter lookup: " << "Ezequiel " << new_b->lookup("Ezequiel") << "\n";
  std::cout << "filter lookup: " << "Noel " << new_b->lookup("Noel") << "\n";
  std::cout << "filter lookup: " << "Pablo " << new_b->lookup("Pablo") << "\n";
  std::cout << "filter lookup: " << "Cade " << new_b->lookup("Cade") << "\n";
  std::cout << "filter lookup: " << "Pedro " << new_b->lookup("Pedro") << "\n";
  std::cout << "filter lookup: " << "Sullivan " << new_b->lookup("Sullivan") << "\n";
  std::cout << "filter lookup: " << "Trevor " << new_b->lookup("Trevor") << "\n";
  std::cout << "filter lookup: " << "Reed " << new_b->lookup("Reed") << "\n";
  std::cout << "filter lookup: " << "Quinn " << new_b->lookup("Quinn") << "\n";
  std::cout << "filter lookup: " << "Frank " << new_b->lookup("Frank") << "\n";
  std::cout << "filter lookup: " << "Harvey " << new_b->lookup("Harvey") << "\n";
  std::cout << "filter lookup: " << "Princeton " << new_b->lookup("Princeton") << "\n";
  std::cout << "filter lookup: " << "Zayne " << new_b->lookup("Zayne") << "\n";
  std::cout << "filter lookup: " << "Matthias " << new_b->lookup("Matthias") << "\n";
  std::cout << "filter lookup: " << "Conor " << new_b->lookup("Conor") << "\n";
  std::cout << "filter lookup: " << "Sterling " << new_b->lookup("Sterling") << "\n";
  std::cout << "filter lookup: " << "Dax " << new_b->lookup("Dax") << "\n";
  std::cout << "filter lookup: " << "Grady " << new_b->lookup("Grady") << "\n";
  std::cout << "filter lookup: " << "Cyrus " << new_b->lookup("Cyrus") << "\n";
  std::cout << "filter lookup: " << "Gage " << new_b->lookup("Gage") << "\n";
  std::cout << "filter lookup: " << "Leland " << new_b->lookup("Leland") << "\n";
  std::cout << "filter lookup: " << "Solomon " << new_b->lookup("Solomon") << "\n";
  std::cout << "filter lookup: " << "Emanuel " << new_b->lookup("Emanuel") << "\n";
  std::cout << "filter lookup: " << "Niko " << new_b->lookup("Niko") << "\n";
  std::cout << "filter lookup: " << "Ruben " << new_b->lookup("Ruben") << "\n";
  std::cout << "filter lookup: " << "Kasen " << new_b->lookup("Kasen") << "\n";
  std::cout << "filter lookup: " << "Mathias " << new_b->lookup("Mathias") << "\n";
  std::cout << "filter lookup: " << "Kashton " << new_b->lookup("Kashton") << "\n";
  std::cout << "filter lookup: " << "Franklin " << new_b->lookup("Franklin") << "\n";
  std::cout << "filter lookup: " << "Remy " << new_b->lookup("Remy") << "\n";
  std::cout << "filter lookup: " << "Shane " << new_b->lookup("Shane") << "\n";
  std::cout << "filter lookup: " << "Kendrick " << new_b->lookup("Kendrick") << "\n";
  std::cout << "filter lookup: " << "Shawn " << new_b->lookup("Shawn") << "\n";
  std::cout << "filter lookup: " << "Otto " << new_b->lookup("Otto") << "\n";
  std::cout << "filter lookup: " << "Armani " << new_b->lookup("Armani") << "\n";
  std::cout << "filter lookup: " << "Keegan " << new_b->lookup("Keegan") << "\n";
  std::cout << "filter lookup: " << "Finnegan " << new_b->lookup("Finnegan") << "\n";
  std::cout << "filter lookup: " << "Memphis " << new_b->lookup("Memphis") << "\n";
  std::cout << "filter lookup: " << "Bowen " << new_b->lookup("Bowen") << "\n";
  std::cout << "filter lookup: " << "Dominick " << new_b->lookup("Dominick") << "\n";
  std::cout << "filter lookup: " << "Kolton " << new_b->lookup("Kolton") << "\n";
  std::cout << "filter lookup: " << "Jamison " << new_b->lookup("Jamison") << "\n";
  std::cout << "filter lookup: " << "Allen " << new_b->lookup("Allen") << "\n";
  std::cout << "filter lookup: " << "Philip " << new_b->lookup("Philip") << "\n";
  std::cout << "filter lookup: " << "Tate " << new_b->lookup("Tate") << "\n";
  std::cout << "filter lookup: " << "Peyton " << new_b->lookup("Peyton") << "\n";
  std::cout << "filter lookup: " << "Jase " << new_b->lookup("Jase") << "\n";
  std::cout << "filter lookup: " << "Oakley " << new_b->lookup("Oakley") << "\n";
  std::cout << "filter lookup: " << "Rhys " << new_b->lookup("Rhys") << "\n";
  std::cout << "filter lookup: " << "Kyson " << new_b->lookup("Kyson") << "\n";
  std::cout << "filter lookup: " << "Adan " << new_b->lookup("Adan") << "\n";
  std::cout << "filter lookup: " << "Esteban " << new_b->lookup("Esteban") << "\n";
  std::cout << "filter lookup: " << "Dalton " << new_b->lookup("Dalton") << "\n";
  std::cout << "filter lookup: " << "Gianni " << new_b->lookup("Gianni") << "\n";
  std::cout << "filter lookup: " << "Callum " << new_b->lookup("Callum") << "\n";
  std::cout << "filter lookup: " << "Sage " << new_b->lookup("Sage") << "\n";
  std::cout << "filter lookup: " << "Alexis " << new_b->lookup("Alexis") << "\n";
  std::cout << "filter lookup: " << "Milan " << new_b->lookup("Milan") << "\n";
  std::cout << "filter lookup: " << "Moises " << new_b->lookup("Moises") << "\n";
  std::cout << "filter lookup: " << "Jonas " << new_b->lookup("Jonas") << "\n";
  std::cout << "filter lookup: " << "Uriel " << new_b->lookup("Uriel") << "\n";
  std::cout << "filter lookup: " << "Colson " << new_b->lookup("Colson") << "\n";
  std::cout << "filter lookup: " << "Marcos " << new_b->lookup("Marcos") << "\n";
  std::cout << "filter lookup: " << "Zaiden " << new_b->lookup("Zaiden") << "\n";
  std::cout << "filter lookup: " << "Hank " << new_b->lookup("Hank") << "\n";
  std::cout << "filter lookup: " << "Damon " << new_b->lookup("Damon") << "\n";
  std::cout << "filter lookup: " << "Hugo " << new_b->lookup("Hugo") << "\n";
  std::cout << "filter lookup: " << "Ronin " << new_b->lookup("Ronin") << "\n";
  std::cout << "filter lookup: " << "Royal " << new_b->lookup("Royal") << "\n";
  std::cout << "filter lookup: " << "Kamden " << new_b->lookup("Kamden") << "\n";
  std::cout << "filter lookup: " << "Dexter " << new_b->lookup("Dexter") << "\n";
  std::cout << "filter lookup: " << "Luciano " << new_b->lookup("Luciano") << "\n";
  std::cout << "filter lookup: " << "Alonzo " << new_b->lookup("Alonzo") << "\n";
  std::cout << "filter lookup: " << "Augustus " << new_b->lookup("Augustus") << "\n";
  std::cout << "filter lookup: " << "Kamari " << new_b->lookup("Kamari") << "\n";
  std::cout << "filter lookup: " << "Eden " << new_b->lookup("Eden") << "\n";
  std::cout << "filter lookup: " << "Roberto " << new_b->lookup("Roberto") << "\n";
  std::cout << "filter lookup: " << "Baker " << new_b->lookup("Baker") << "\n";
  std::cout << "filter lookup: " << "Bruce " << new_b->lookup("Bruce") << "\n";
  std::cout << "filter lookup: " << "Kian " << new_b->lookup("Kian") << "\n";
  std::cout << "filter lookup: " << "Albert " << new_b->lookup("Albert") << "\n";
  std::cout << "filter lookup: " << "Frederick " << new_b->lookup("Frederick") << "\n";
  std::cout << "filter lookup: " << "Mohamed " << new_b->lookup("Mohamed") << "\n";
  std::cout << "filter lookup: " << "Abram " << new_b->lookup("Abram") << "\n";
  std::cout << "filter lookup: " << "Omari " << new_b->lookup("Omari") << "\n";
  std::cout << "filter lookup: " << "Porter " << new_b->lookup("Porter") << "\n";
  std::cout << "filter lookup: " << "Enrique " << new_b->lookup("Enrique") << "\n";
  std::cout << "filter lookup: " << "Alijah " << new_b->lookup("Alijah") << "\n";
  std::cout << "filter lookup: " << "Francis " << new_b->lookup("Francis") << "\n";
  std::cout << "filter lookup: " << "Leonidas " << new_b->lookup("Leonidas") << "\n";
  std::cout << "filter lookup: " << "Zachariah " << new_b->lookup("Zachariah") << "\n";
  std::cout << "filter lookup: " << "Landen " << new_b->lookup("Landen") << "\n";
  std::cout << "filter lookup: " << "Wilder " << new_b->lookup("Wilder") << "\n";
  std::cout << "filter lookup: " << "Apollo " << new_b->lookup("Apollo") << "\n";
  std::cout << "filter lookup: " << "Santino " << new_b->lookup("Santino") << "\n";
  std::cout << "filter lookup: " << "Tatum " << new_b->lookup("Tatum") << "\n";
  std::cout << "filter lookup: " << "Pierce " << new_b->lookup("Pierce") << "\n";
  std::cout << "filter lookup: " << "Forrest " << new_b->lookup("Forrest") << "\n";
  std::cout << "filter lookup: " << "Corey " << new_b->lookup("Corey") << "\n";
  std::cout << "filter lookup: " << "Derrick " << new_b->lookup("Derrick") << "\n";
  std::cout << "filter lookup: " << "Isaias " << new_b->lookup("Isaias") << "\n";
  std::cout << "filter lookup: " << "Kaison " << new_b->lookup("Kaison") << "\n";
  std::cout << "filter lookup: " << "Kieran " << new_b->lookup("Kieran") << "\n";
  std::cout << "filter lookup: " << "Arjun " << new_b->lookup("Arjun") << "\n";
  std::cout << "filter lookup: " << "Gunnar " << new_b->lookup("Gunnar") << "\n";
  std::cout << "filter lookup: " << "Rocco " << new_b->lookup("Rocco") << "\n";
  std::cout << "filter lookup: " << "Emmitt " << new_b->lookup("Emmitt") << "\n";
  std::cout << "filter lookup: " << "Abdiel " << new_b->lookup("Abdiel") << "\n";
  std::cout << "filter lookup: " << "Braylen " << new_b->lookup("Braylen") << "\n";
  std::cout << "filter lookup: " << "Maximilian " << new_b->lookup("Maximilian") << "\n";
  std::cout << "filter lookup: " << "Skyler " << new_b->lookup("Skyler") << "\n";
  std::cout << "filter lookup: " << "Phillip " << new_b->lookup("Phillip") << "\n";
  std::cout << "filter lookup: " << "Benson " << new_b->lookup("Benson") << "\n";
  std::cout << "filter lookup: " << "Cannon " << new_b->lookup("Cannon") << "\n";
  std::cout << "filter lookup: " << "Deacon " << new_b->lookup("Deacon") << "\n";
  std::cout << "filter lookup: " << "Dorian " << new_b->lookup("Dorian") << "\n";
  std::cout << "filter lookup: " << "Asa " << new_b->lookup("Asa") << "\n";
  std::cout << "filter lookup: " << "Moses " << new_b->lookup("Moses") << "\n";
  std::cout << "filter lookup: " << "Ayaan " << new_b->lookup("Ayaan") << "\n";
  std::cout << "filter lookup: " << "Jayson " << new_b->lookup("Jayson") << "\n";
  std::cout << "filter lookup: " << "Raul " << new_b->lookup("Raul") << "\n";
  std::cout << "filter lookup: " << "Briggs " << new_b->lookup("Briggs") << "\n";
  std::cout << "filter lookup: " << "Armando " << new_b->lookup("Armando") << "\n";
  std::cout << "filter lookup: " << "Nikolai " << new_b->lookup("Nikolai") << "\n";
  std::cout << "filter lookup: " << "Cassius " << new_b->lookup("Cassius") << "\n";
  std::cout << "filter lookup: " << "Drew " << new_b->lookup("Drew") << "\n";
  std::cout << "filter lookup: " << "Rodrigo " << new_b->lookup("Rodrigo") << "\n";
  std::cout << "filter lookup: " << "Raphael " << new_b->lookup("Raphael") << "\n";
  std::cout << "filter lookup: " << "Danny " << new_b->lookup("Danny") << "\n";
  std::cout << "filter lookup: " << "Conrad " << new_b->lookup("Conrad") << "\n";
  std::cout << "filter lookup: " << "Moshe " << new_b->lookup("Moshe") << "\n";
  std::cout << "filter lookup: " << "Zyaire " << new_b->lookup("Zyaire") << "\n";
  std::cout << "filter lookup: " << "Julio " << new_b->lookup("Julio") << "\n";
  std::cout << "filter lookup: " << "Casey " << new_b->lookup("Casey") << "\n";
  std::cout << "filter lookup: " << "Ronald " << new_b->lookup("Ronald") << "\n";
  std::cout << "filter lookup: " << "Scott " << new_b->lookup("Scott") << "\n";
  std::cout << "filter lookup: " << "Callan " << new_b->lookup("Callan") << "\n";
  std::cout << "filter lookup: " << "Roland " << new_b->lookup("Roland") << "\n";
  std::cout << "filter lookup: " << "Saul " << new_b->lookup("Saul") << "\n";
  std::cout << "filter lookup: " << "Jalen " << new_b->lookup("Jalen") << "\n";
  std::cout << "filter lookup: " << "Brycen " << new_b->lookup("Brycen") << "\n";
  std::cout << "filter lookup: " << "Ryland " << new_b->lookup("Ryland") << "\n";
  std::cout << "filter lookup: " << "Lawrence " << new_b->lookup("Lawrence") << "\n";
  std::cout << "filter lookup: " << "Davis " << new_b->lookup("Davis") << "\n";
  std::cout << "filter lookup: " << "Rowen " << new_b->lookup("Rowen") << "\n";
  std::cout << "filter lookup: " << "Zain " << new_b->lookup("Zain") << "\n";
  std::cout << "filter lookup: " << "Ermias " << new_b->lookup("Ermias") << "\n";
  std::cout << "filter lookup: " << "Jaime " << new_b->lookup("Jaime") << "\n";
  std::cout << "filter lookup: " << "Duke " << new_b->lookup("Duke") << "\n";
  std::cout << "filter lookup: " << "Stetson " << new_b->lookup("Stetson") << "\n";
  std::cout << "filter lookup: " << "Alec " << new_b->lookup("Alec") << "\n";
  std::cout << "filter lookup: " << "Yusuf " << new_b->lookup("Yusuf") << "\n";
  std::cout << "filter lookup: " << "Case " << new_b->lookup("Case") << "\n";
  std::cout << "filter lookup: " << "Trenton " << new_b->lookup("Trenton") << "\n";
  std::cout << "filter lookup: " << "Callen " << new_b->lookup("Callen") << "\n";
  std::cout << "filter lookup: " << "Ariel " << new_b->lookup("Ariel") << "\n";
  std::cout << "filter lookup: " << "Jasiah " << new_b->lookup("Jasiah") << "\n";
  std::cout << "filter lookup: " << "Soren " << new_b->lookup("Soren") << "\n";
  std::cout << "filter lookup: " << "Dennis " << new_b->lookup("Dennis") << "\n";
  std::cout << "filter lookup: " << "Donald " << new_b->lookup("Donald") << "\n";
  std::cout << "filter lookup: " << "Keith " << new_b->lookup("Keith") << "\n";
  std::cout << "filter lookup: " << "Izaiah " << new_b->lookup("Izaiah") << "\n";
  std::cout << "filter lookup: " << "Lewis " << new_b->lookup("Lewis") << "\n";
  std::cout << "filter lookup: " << "Kylan " << new_b->lookup("Kylan") << "\n";
  std::cout << "filter lookup: " << "Kobe " << new_b->lookup("Kobe") << "\n";
  std::cout << "filter lookup: " << "Makai " << new_b->lookup("Makai") << "\n";
  std::cout << "filter lookup: " << "Rayan " << new_b->lookup("Rayan") << "\n";
  std::cout << "filter lookup: " << "Ford " << new_b->lookup("Ford") << "\n";
  std::cout << "filter lookup: " << "Zaire " << new_b->lookup("Zaire") << "\n";
  std::cout << "filter lookup: " << "Landyn " << new_b->lookup("Landyn") << "\n";
  std::cout << "filter lookup: " << "Roy " << new_b->lookup("Roy") << "\n";
  std::cout << "filter lookup: " << "Bo " << new_b->lookup("Bo") << "\n";
  std::cout << "filter lookup: " << "Chris " << new_b->lookup("Chris") << "\n";
  std::cout << "filter lookup: " << "Jamari " << new_b->lookup("Jamari") << "\n";
  std::cout << "filter lookup: " << "Ares " << new_b->lookup("Ares") << "\n";
  std::cout << "filter lookup: " << "Mohammad " << new_b->lookup("Mohammad") << "\n";
  std::cout << "filter lookup: " << "Darius " << new_b->lookup("Darius") << "\n";
  std::cout << "filter lookup: " << "Drake " << new_b->lookup("Drake") << "\n";
  std::cout << "filter lookup: " << "Tripp " << new_b->lookup("Tripp") << "\n";
  std::cout << "filter lookup: " << "Marcelo " << new_b->lookup("Marcelo") << "\n";
  std::cout << "filter lookup: " << "Samson " << new_b->lookup("Samson") << "\n";
  std::cout << "filter lookup: " << "Dustin " << new_b->lookup("Dustin") << "\n";
  std::cout << "filter lookup: " << "Layton " << new_b->lookup("Layton") << "\n";
  std::cout << "filter lookup: " << "Gerardo " << new_b->lookup("Gerardo") << "\n";
  std::cout << "filter lookup: " << "Johan " << new_b->lookup("Johan") << "\n";
  std::cout << "filter lookup: " << "Kaysen " << new_b->lookup("Kaysen") << "\n";
  std::cout << "filter lookup: " << "Keaton " << new_b->lookup("Keaton") << "\n";
  std::cout << "filter lookup: " << "Reece " << new_b->lookup("Reece") << "\n";
  std::cout << "filter lookup: " << "Chandler " << new_b->lookup("Chandler") << "\n";
  std::cout << "filter lookup: " << "Lucca " << new_b->lookup("Lucca") << "\n";
  std::cout << "filter lookup: " << "Mack " << new_b->lookup("Mack") << "\n";
  std::cout << "filter lookup: " << "Baylor " << new_b->lookup("Baylor") << "\n";
  std::cout << "filter lookup: " << "Kannon " << new_b->lookup("Kannon") << "\n";
  std::cout << "filter lookup: " << "Marvin " << new_b->lookup("Marvin") << "\n";
  std::cout << "filter lookup: " << "Huxley " << new_b->lookup("Huxley") << "\n";
  std::cout << "filter lookup: " << "Nixon " << new_b->lookup("Nixon") << "\n";
  std::cout << "filter lookup: " << "Tony " << new_b->lookup("Tony") << "\n";
  std::cout << "filter lookup: " << "Cason " << new_b->lookup("Cason") << "\n";
  std::cout << "filter lookup: " << "Mauricio " << new_b->lookup("Mauricio") << "\n";
  std::cout << "filter lookup: " << "Quentin " << new_b->lookup("Quentin") << "\n";
  std::cout << "filter lookup: " << "Edison " << new_b->lookup("Edison") << "\n";
  std::cout << "filter lookup: " << "Quincy " << new_b->lookup("Quincy") << "\n";
  std::cout << "filter lookup: " << "Ahmed " << new_b->lookup("Ahmed") << "\n";
  std::cout << "filter lookup: " << "Finnley " << new_b->lookup("Finnley") << "\n";
  std::cout << "filter lookup: " << "Justice " << new_b->lookup("Justice") << "\n";
  std::cout << "filter lookup: " << "Taylor " << new_b->lookup("Taylor") << "\n";
  std::cout << "filter lookup: " << "Gustavo " << new_b->lookup("Gustavo") << "\n";
  std::cout << "filter lookup: " << "Brock " << new_b->lookup("Brock") << "\n";
  std::cout << "filter lookup: " << "Ahmad " << new_b->lookup("Ahmad") << "\n";
  std::cout << "filter lookup: " << "Kyree " << new_b->lookup("Kyree") << "\n";
  std::cout << "filter lookup: " << "Arturo " << new_b->lookup("Arturo") << "\n";
  std::cout << "filter lookup: " << "Nikolas " << new_b->lookup("Nikolas") << "\n";
  std::cout << "filter lookup: " << "Boston " << new_b->lookup("Boston") << "\n";
  std::cout << "filter lookup: " << "Sincere " << new_b->lookup("Sincere") << "\n";
  std::cout << "filter lookup: " << "Alessandro " << new_b->lookup("Alessandro") << "\n";
  std::cout << "filter lookup: " << "Braylon " << new_b->lookup("Braylon") << "\n";
  std::cout << "filter lookup: " << "Colby " << new_b->lookup("Colby") << "\n";
  std::cout << "filter lookup: " << "Leonard " << new_b->lookup("Leonard") << "\n";
  std::cout << "filter lookup: " << "Ridge " << new_b->lookup("Ridge") << "\n";
  std::cout << "filter lookup: " << "Trey " << new_b->lookup("Trey") << "\n";
  std::cout << "filter lookup: " << "Aden " << new_b->lookup("Aden") << "\n";
  std::cout << "filter lookup: " << "Leandro " << new_b->lookup("Leandro") << "\n";
  std::cout << "filter lookup: " << "Sam " << new_b->lookup("Sam") << "\n";
  std::cout << "filter lookup: " << "Uriah " << new_b->lookup("Uriah") << "\n";
  std::cout << "filter lookup: " << "Ty " << new_b->lookup("Ty") << "\n";
  std::cout << "filter lookup: " << "Sylas " << new_b->lookup("Sylas") << "\n";
  std::cout << "filter lookup: " << "Axton " << new_b->lookup("Axton") << "\n";
  std::cout << "filter lookup: " << "Issac " << new_b->lookup("Issac") << "\n";
  std::cout << "filter lookup: " << "Fletcher " << new_b->lookup("Fletcher") << "\n";
  std::cout << "filter lookup: " << "Julien " << new_b->lookup("Julien") << "\n";
  std::cout << "filter lookup: " << "Wells " << new_b->lookup("Wells") << "\n";
  std::cout << "filter lookup: " << "Alden " << new_b->lookup("Alden") << "\n";
  std::cout << "filter lookup: " << "Vihaan " << new_b->lookup("Vihaan") << "\n";
  std::cout << "filter lookup: " << "Jamir " << new_b->lookup("Jamir") << "\n";
  std::cout << "filter lookup: " << "Valentino " << new_b->lookup("Valentino") << "\n";
  std::cout << "filter lookup: " << "Shepherd " << new_b->lookup("Shepherd") << "\n";
  std::cout << "filter lookup: " << "Keanu " << new_b->lookup("Keanu") << "\n";
  std::cout << "filter lookup: " << "Hezekiah " << new_b->lookup("Hezekiah") << "\n";
  std::cout << "filter lookup: " << "Lionel " << new_b->lookup("Lionel") << "\n";
  std::cout << "filter lookup: " << "Kohen " << new_b->lookup("Kohen") << "\n";
  std::cout << "filter lookup: " << "Zaid " << new_b->lookup("Zaid") << "\n";
  std::cout << "filter lookup: " << "Alberto " << new_b->lookup("Alberto") << "\n";
  std::cout << "filter lookup: " << "Neil " << new_b->lookup("Neil") << "\n";
  std::cout << "filter lookup: " << "Denver " << new_b->lookup("Denver") << "\n";
  std::cout << "filter lookup: " << "Aarav " << new_b->lookup("Aarav") << "\n";
  std::cout << "filter lookup: " << "Brendan " << new_b->lookup("Brendan") << "\n";
  std::cout << "filter lookup: " << "Dillon " << new_b->lookup("Dillon") << "\n";
  std::cout << "filter lookup: " << "Koda " << new_b->lookup("Koda") << "\n";
  std::cout << "filter lookup: " << "Sutton " << new_b->lookup("Sutton") << "\n";
  std::cout << "filter lookup: " << "Kingsley " << new_b->lookup("Kingsley") << "\n";
  std::cout << "filter lookup: " << "Sonny " << new_b->lookup("Sonny") << "\n";
  std::cout << "filter lookup: " << "Alfredo " << new_b->lookup("Alfredo") << "\n";
  std::cout << "filter lookup: " << "Wilson " << new_b->lookup("Wilson") << "\n";
  std::cout << "filter lookup: " << "Harry " << new_b->lookup("Harry") << "\n";
  std::cout << "filter lookup: " << "Jaziel " << new_b->lookup("Jaziel") << "\n";
  std::cout << "filter lookup: " << "Salvador " << new_b->lookup("Salvador") << "\n";
  std::cout << "filter lookup: " << "Cullen " << new_b->lookup("Cullen") << "\n";
  std::cout << "filter lookup: " << "Hamza " << new_b->lookup("Hamza") << "\n";
  std::cout << "filter lookup: " << "Dariel " << new_b->lookup("Dariel") << "\n";
  std::cout << "filter lookup: " << "Rex " << new_b->lookup("Rex") << "\n";
  std::cout << "filter lookup: " << "Zeke " << new_b->lookup("Zeke") << "\n";
  std::cout << "filter lookup: " << "Mohammed " << new_b->lookup("Mohammed") << "\n";
  std::cout << "filter lookup: " << "Nelson " << new_b->lookup("Nelson") << "\n";
  std::cout << "filter lookup: " << "Boone " << new_b->lookup("Boone") << "\n";
  std::cout << "filter lookup: " << "Ricky " << new_b->lookup("Ricky") << "\n";
  std::cout << "filter lookup: " << "Santana " << new_b->lookup("Santana") << "\n";
  std::cout << "filter lookup: " << "Cayson " << new_b->lookup("Cayson") << "\n";
  std::cout << "filter lookup: " << "Lance " << new_b->lookup("Lance") << "\n";
  std::cout << "filter lookup: " << "Raylan " << new_b->lookup("Raylan") << "\n";
  std::cout << "filter lookup: " << "Lucian " << new_b->lookup("Lucian") << "\n";
  std::cout << "filter lookup: " << "Eliel " << new_b->lookup("Eliel") << "\n";
  std::cout << "filter lookup: " << "Alvin " << new_b->lookup("Alvin") << "\n";
  std::cout << "filter lookup: " << "Jagger " << new_b->lookup("Jagger") << "\n";
  std::cout << "filter lookup: " << "Braden " << new_b->lookup("Braden") << "\n";
  std::cout << "filter lookup: " << "Curtis " << new_b->lookup("Curtis") << "\n";
  std::cout << "filter lookup: " << "Mathew " << new_b->lookup("Mathew") << "\n";
  std::cout << "filter lookup: " << "Jimmy " << new_b->lookup("Jimmy") << "\n";
  std::cout << "filter lookup: " << "Kareem " << new_b->lookup("Kareem") << "\n";
  std::cout << "filter lookup: " << "Archie " << new_b->lookup("Archie") << "\n";
  std::cout << "filter lookup: " << "Amos " << new_b->lookup("Amos") << "\n";
  std::cout << "filter lookup: " << "Quinton " << new_b->lookup("Quinton") << "\n";
  std::cout << "filter lookup: " << "Yosef " << new_b->lookup("Yosef") << "\n";
  std::cout << "filter lookup: " << "Bodie " << new_b->lookup("Bodie") << "\n";
  std::cout << "filter lookup: " << "Jerry " << new_b->lookup("Jerry") << "\n";
  std::cout << "filter lookup: " << "Langston " << new_b->lookup("Langston") << "\n";
  std::cout << "filter lookup: " << "Axl " << new_b->lookup("Axl") << "\n";
  std::cout << "filter lookup: " << "Stanley " << new_b->lookup("Stanley") << "\n";
  std::cout << "filter lookup: " << "Clay " << new_b->lookup("Clay") << "\n";
  std::cout << "filter lookup: " << "Douglas " << new_b->lookup("Douglas") << "\n";
  std::cout << "filter lookup: " << "Layne " << new_b->lookup("Layne") << "\n";
  std::cout << "filter lookup: " << "Titan " << new_b->lookup("Titan") << "\n";
  std::cout << "filter lookup: " << "Tomas " << new_b->lookup("Tomas") << "\n";
  std::cout << "filter lookup: " << "Houston " << new_b->lookup("Houston") << "\n";
  std::cout << "filter lookup: " << "Darren " << new_b->lookup("Darren") << "\n";
  std::cout << "filter lookup: " << "Lachlan " << new_b->lookup("Lachlan") << "\n";
  std::cout << "filter lookup: " << "Kase " << new_b->lookup("Kase") << "\n";
  std::cout << "filter lookup: " << "Korbin " << new_b->lookup("Korbin") << "\n";
  std::cout << "filter lookup: " << "Leighton " << new_b->lookup("Leighton") << "\n";
  std::cout << "filter lookup: " << "Joziah " << new_b->lookup("Joziah") << "\n";
  std::cout << "filter lookup: " << "Samir " << new_b->lookup("Samir") << "\n";
  std::cout << "filter lookup: " << "Watson " << new_b->lookup("Watson") << "\n";
  std::cout << "filter lookup: " << "Colten " << new_b->lookup("Colten") << "\n";
  std::cout << "filter lookup: " << "Roger " << new_b->lookup("Roger") << "\n";
  std::cout << "filter lookup: " << "Shiloh " << new_b->lookup("Shiloh") << "\n";
  std::cout << "filter lookup: " << "Tommy " << new_b->lookup("Tommy") << "\n";
  std::cout << "filter lookup: " << "Mitchell " << new_b->lookup("Mitchell") << "\n";
  std::cout << "filter lookup: " << "Azariah " << new_b->lookup("Azariah") << "\n";
  std::cout << "filter lookup: " << "Noe " << new_b->lookup("Noe") << "\n";
  std::cout << "filter lookup: " << "Talon " << new_b->lookup("Talon") << "\n";
  std::cout << "filter lookup: " << "Deandre " << new_b->lookup("Deandre") << "\n";
  std::cout << "filter lookup: " << "Lochlan " << new_b->lookup("Lochlan") << "\n";
  std::cout << "filter lookup: " << "Joe " << new_b->lookup("Joe") << "\n";
  std::cout << "filter lookup: " << "Carmelo " << new_b->lookup("Carmelo") << "\n";
  std::cout << "filter lookup: " << "Otis " << new_b->lookup("Otis") << "\n";
  std::cout << "filter lookup: " << "Randy " << new_b->lookup("Randy") << "\n";
  std::cout << "filter lookup: " << "Byron " << new_b->lookup("Byron") << "\n";
  std::cout << "filter lookup: " << "Chaim " << new_b->lookup("Chaim") << "\n";
  std::cout << "filter lookup: " << "Lennon " << new_b->lookup("Lennon") << "\n";
  std::cout << "filter lookup: " << "Devon " << new_b->lookup("Devon") << "\n";
  std::cout << "filter lookup: " << "Nathanael " << new_b->lookup("Nathanael") << "\n";
  std::cout << "filter lookup: " << "Bruno " << new_b->lookup("Bruno") << "\n";
  std::cout << "filter lookup: " << "Aryan " << new_b->lookup("Aryan") << "\n";
  std::cout << "filter lookup: " << "Flynn " << new_b->lookup("Flynn") << "\n";
  std::cout << "filter lookup: " << "Vicente " << new_b->lookup("Vicente") << "\n";
  std::cout << "filter lookup: " << "Brixton " << new_b->lookup("Brixton") << "\n";
  std::cout << "filter lookup: " << "Kyro " << new_b->lookup("Kyro") << "\n";
  std::cout << "filter lookup: " << "Brennan " << new_b->lookup("Brennan") << "\n";
  std::cout << "filter lookup: " << "Casen " << new_b->lookup("Casen") << "\n";
  std::cout << "filter lookup: " << "Kenzo " << new_b->lookup("Kenzo") << "\n";
  std::cout << "filter lookup: " << "Orlando " << new_b->lookup("Orlando") << "\n";
  std::cout << "filter lookup: " << "Castiel " << new_b->lookup("Castiel") << "\n";
  std::cout << "filter lookup: " << "Rayden " << new_b->lookup("Rayden") << "\n";
  std::cout << "filter lookup: " << "Ben " << new_b->lookup("Ben") << "\n";
  std::cout << "filter lookup: " << "Grey " << new_b->lookup("Grey") << "\n";
  std::cout << "filter lookup: " << "Jedidiah " << new_b->lookup("Jedidiah") << "\n";
  std::cout << "filter lookup: " << "Tadeo " << new_b->lookup("Tadeo") << "\n";
  std::cout << "filter lookup: " << "Morgan " << new_b->lookup("Morgan") << "\n";
  std::cout << "filter lookup: " << "Augustine " << new_b->lookup("Augustine") << "\n";
  std::cout << "filter lookup: " << "Mekhi " << new_b->lookup("Mekhi") << "\n";
  std::cout << "filter lookup: " << "Abdullah " << new_b->lookup("Abdullah") << "\n";
  std::cout << "filter lookup: " << "Ramon " << new_b->lookup("Ramon") << "\n";
  std::cout << "filter lookup: " << "Saint " << new_b->lookup("Saint") << "\n";
  std::cout << "filter lookup: " << "Emery " << new_b->lookup("Emery") << "\n";
  std::cout << "filter lookup: " << "Maurice " << new_b->lookup("Maurice") << "\n";
  std::cout << "filter lookup: " << "Jefferson " << new_b->lookup("Jefferson") << "\n";
  std::cout << "filter lookup: " << "Maximo " << new_b->lookup("Maximo") << "\n";
  std::cout << "filter lookup: " << "Koa " << new_b->lookup("Koa") << "\n";
  std::cout << "filter lookup: " << "Ray " << new_b->lookup("Ray") << "\n";
  std::cout << "filter lookup: " << "Jamie " << new_b->lookup("Jamie") << "\n";
  std::cout << "filter lookup: " << "Eddie " << new_b->lookup("Eddie") << "\n";
  std::cout << "filter lookup: " << "Guillermo " << new_b->lookup("Guillermo") << "\n";
  std::cout << "filter lookup: " << "Onyx " << new_b->lookup("Onyx") << "\n";
  std::cout << "filter lookup: " << "Thaddeus " << new_b->lookup("Thaddeus") << "\n";
  std::cout << "filter lookup: " << "Wayne " << new_b->lookup("Wayne") << "\n";
  std::cout << "filter lookup: " << "Hassan " << new_b->lookup("Hassan") << "\n";
  std::cout << "filter lookup: " << "Alonso " << new_b->lookup("Alonso") << "\n";
  std::cout << "filter lookup: " << "Dash " << new_b->lookup("Dash") << "\n";
  std::cout << "filter lookup: " << "Elisha " << new_b->lookup("Elisha") << "\n";
  std::cout << "filter lookup: " << "Jaxxon " << new_b->lookup("Jaxxon") << "\n";
  std::cout << "filter lookup: " << "Rohan " << new_b->lookup("Rohan") << "\n";
  std::cout << "filter lookup: " << "Carl " << new_b->lookup("Carl") << "\n";
  std::cout << "filter lookup: " << "Kelvin " << new_b->lookup("Kelvin") << "\n";
  std::cout << "filter lookup: " << "Jon " << new_b->lookup("Jon") << "\n";
  std::cout << "filter lookup: " << "Larry " << new_b->lookup("Larry") << "\n";
  std::cout << "filter lookup: " << "Reese " << new_b->lookup("Reese") << "\n";
  std::cout << "filter lookup: " << "Aldo " << new_b->lookup("Aldo") << "\n";
  std::cout << "filter lookup: " << "Marcel " << new_b->lookup("Marcel") << "\n";
  std::cout << "filter lookup: " << "Melvin " << new_b->lookup("Melvin") << "\n";
  std::cout << "filter lookup: " << "Yousef " << new_b->lookup("Yousef") << "\n";
  std::cout << "filter lookup: " << "Aron " << new_b->lookup("Aron") << "\n";
  std::cout << "filter lookup: " << "Kace " << new_b->lookup("Kace") << "\n";
  std::cout << "filter lookup: " << "Vincenzo " << new_b->lookup("Vincenzo") << "\n";
  std::cout << "filter lookup: " << "Kellan " << new_b->lookup("Kellan") << "\n";
  std::cout << "filter lookup: " << "Miller " << new_b->lookup("Miller") << "\n";
  std::cout << "filter lookup: " << "Jakob " << new_b->lookup("Jakob") << "\n";
  std::cout << "filter lookup: " << "Reign " << new_b->lookup("Reign") << "\n";
  std::cout << "filter lookup: " << "Kellen " << new_b->lookup("Kellen") << "\n";
  std::cout << "filter lookup: " << "Kristopher " << new_b->lookup("Kristopher") << "\n";
  std::cout << "filter lookup: " << "Ernesto " << new_b->lookup("Ernesto") << "\n";
  std::cout << "filter lookup: " << "Briar " << new_b->lookup("Briar") << "\n";
  std::cout << "filter lookup: " << "Gary " << new_b->lookup("Gary") << "\n";
  std::cout << "filter lookup: " << "Trace " << new_b->lookup("Trace") << "\n";
  std::cout << "filter lookup: " << "Joey " << new_b->lookup("Joey") << "\n";
  std::cout << "filter lookup: " << "Clyde " << new_b->lookup("Clyde") << "\n";
  std::cout << "filter lookup: " << "Enoch " << new_b->lookup("Enoch") << "\n";
  std::cout << "filter lookup: " << "Jaxx " << new_b->lookup("Jaxx") << "\n";
  std::cout << "filter lookup: " << "Crosby " << new_b->lookup("Crosby") << "\n";
  std::cout << "filter lookup: " << "Magnus " << new_b->lookup("Magnus") << "\n";
  std::cout << "filter lookup: " << "Fisher " << new_b->lookup("Fisher") << "\n";
  std::cout << "filter lookup: " << "Jadiel " << new_b->lookup("Jadiel") << "\n";
  std::cout << "filter lookup: " << "Bronson " << new_b->lookup("Bronson") << "\n";
  std::cout << "filter lookup: " << "Eugene " << new_b->lookup("Eugene") << "\n";
  std::cout << "filter lookup: " << "Lee " << new_b->lookup("Lee") << "\n";
  std::cout << "filter lookup: " << "Brecken " << new_b->lookup("Brecken") << "\n";
  std::cout << "filter lookup: " << "Atreus " << new_b->lookup("Atreus") << "\n";
  std::cout << "filter lookup: " << "Madden " << new_b->lookup("Madden") << "\n";
  std::cout << "filter lookup: " << "Khari " << new_b->lookup("Khari") << "\n";
  std::cout << "filter lookup: " << "Caspian " << new_b->lookup("Caspian") << "\n";
  std::cout << "filter lookup: " << "Ishaan " << new_b->lookup("Ishaan") << "\n";
  std::cout << "filter lookup: " << "Kristian " << new_b->lookup("Kristian") << "\n";
  std::cout << "filter lookup: " << "Westley " << new_b->lookup("Westley") << "\n";
  std::cout << "filter lookup: " << "Hugh " << new_b->lookup("Hugh") << "\n";
  std::cout << "filter lookup: " << "Kamryn " << new_b->lookup("Kamryn") << "\n";
  std::cout << "filter lookup: " << "Musa " << new_b->lookup("Musa") << "\n";
  std::cout << "filter lookup: " << "Rey " << new_b->lookup("Rey") << "\n";
  std::cout << "filter lookup: " << "Thatcher " << new_b->lookup("Thatcher") << "\n";
  std::cout << "filter lookup: " << "Alfred " << new_b->lookup("Alfred") << "\n";
  std::cout << "filter lookup: " << "Emory " << new_b->lookup("Emory") << "\n";
  std::cout << "filter lookup: " << "Kye " << new_b->lookup("Kye") << "\n";
  std::cout << "filter lookup: " << "Reyansh " << new_b->lookup("Reyansh") << "\n";
  std::cout << "filter lookup: " << "Yahir " << new_b->lookup("Yahir") << "\n";
  std::cout << "filter lookup: " << "Cain " << new_b->lookup("Cain") << "\n";
  std::cout << "filter lookup: " << "Mordechai " << new_b->lookup("Mordechai") << "\n";
  std::cout << "filter lookup: " << "Zayd " << new_b->lookup("Zayd") << "\n";
  std::cout << "filter lookup: " << "Demetrius " << new_b->lookup("Demetrius") << "\n";
  std::cout << "filter lookup: " << "Harley " << new_b->lookup("Harley") << "\n";
  std::cout << "filter lookup: " << "Felipe " << new_b->lookup("Felipe") << "\n";
  std::cout << "filter lookup: " << "Louie " << new_b->lookup("Louie") << "\n";
  std::cout << "filter lookup: " << "Branson " << new_b->lookup("Branson") << "\n";
  std::cout << "filter lookup: " << "Graysen " << new_b->lookup("Graysen") << "\n";
  std::cout << "filter lookup: " << "Allan " << new_b->lookup("Allan") << "\n";
  std::cout << "filter lookup: " << "Kole " << new_b->lookup("Kole") << "\n";
  std::cout << "filter lookup: " << "Harold " << new_b->lookup("Harold") << "\n";
  std::cout << "filter lookup: " << "Alvaro " << new_b->lookup("Alvaro") << "\n";
  std::cout << "filter lookup: " << "Harlan " << new_b->lookup("Harlan") << "\n";
  std::cout << "filter lookup: " << "Amias " << new_b->lookup("Amias") << "\n";
  std::cout << "filter lookup: " << "Brett " << new_b->lookup("Brett") << "\n";
  std::cout << "filter lookup: " << "Khalid " << new_b->lookup("Khalid") << "\n";
  std::cout << "filter lookup: " << "Misael " << new_b->lookup("Misael") << "\n";
  std::cout << "filter lookup: " << "Westin " << new_b->lookup("Westin") << "\n";
  std::cout << "filter lookup: " << "Zechariah " << new_b->lookup("Zechariah") << "\n";
  std::cout << "filter lookup: " << "Aydin " << new_b->lookup("Aydin") << "\n";
  std::cout << "filter lookup: " << "Kaiser " << new_b->lookup("Kaiser") << "\n";
  std::cout << "filter lookup: " << "Lian " << new_b->lookup("Lian") << "\n";
  std::cout << "filter lookup: " << "Bryant " << new_b->lookup("Bryant") << "\n";
  std::cout << "filter lookup: " << "Junior " << new_b->lookup("Junior") << "\n";
  std::cout << "filter lookup: " << "Legacy " << new_b->lookup("Legacy") << "\n";
  std::cout << "filter lookup: " << "Ulises " << new_b->lookup("Ulises") << "\n";
  std::cout << "filter lookup: " << "Bellamy " << new_b->lookup("Bellamy") << "\n";
  std::cout << "filter lookup: " << "Brayan " << new_b->lookup("Brayan") << "\n";
  std::cout << "filter lookup: " << "Kody " << new_b->lookup("Kody") << "\n";
  std::cout << "filter lookup: " << "Ledger " << new_b->lookup("Ledger") << "\n";
  std::cout << "filter lookup: " << "Eliseo " << new_b->lookup("Eliseo") << "\n";
  std::cout << "filter lookup: " << "Gordon " << new_b->lookup("Gordon") << "\n";
  std::cout << "filter lookup: " << "London " << new_b->lookup("London") << "\n";
  std::cout << "filter lookup: " << "Rocky " << new_b->lookup("Rocky") << "\n";
  std::cout << "filter lookup: " << "Valentin " << new_b->lookup("Valentin") << "\n";
  std::cout << "filter lookup: " << "Terry " << new_b->lookup("Terry") << "\n";
  std::cout << "filter lookup: " << "Damari " << new_b->lookup("Damari") << "\n";
  std::cout << "filter lookup: " << "Trent " << new_b->lookup("Trent") << "\n";
  std::cout << "filter lookup: " << "Bentlee " << new_b->lookup("Bentlee") << "\n";
  std::cout << "filter lookup: " << "Canaan " << new_b->lookup("Canaan") << "\n";
  std::cout << "filter lookup: " << "Gatlin " << new_b->lookup("Gatlin") << "\n";
  std::cout << "filter lookup: " << "Kiaan " << new_b->lookup("Kiaan") << "\n";
  std::cout << "filter lookup: " << "Franco " << new_b->lookup("Franco") << "\n";
  std::cout << "filter lookup: " << "Eithan " << new_b->lookup("Eithan") << "\n";
  std::cout << "filter lookup: " << "Idris " << new_b->lookup("Idris") << "\n";
  std::cout << "filter lookup: " << "Krew " << new_b->lookup("Krew") << "\n";
  std::cout << "filter lookup: " << "Yehuda " << new_b->lookup("Yehuda") << "\n";
  std::cout << "filter lookup: " << "Marlon " << new_b->lookup("Marlon") << "\n";
  std::cout << "filter lookup: " << "Rodney " << new_b->lookup("Rodney") << "\n";
  std::cout << "filter lookup: " << "Creed " << new_b->lookup("Creed") << "\n";
  std::cout << "filter lookup: " << "Salvatore " << new_b->lookup("Salvatore") << "\n";
  std::cout << "filter lookup: " << "Stefan " << new_b->lookup("Stefan") << "\n";
  std::cout << "filter lookup: " << "Tristen " << new_b->lookup("Tristen") << "\n";
  std::cout << "filter lookup: " << "Adrien " << new_b->lookup("Adrien") << "\n";
  std::cout << "filter lookup: " << "Jamal " << new_b->lookup("Jamal") << "\n";
  std::cout << "filter lookup: " << "Judson " << new_b->lookup("Judson") << "\n";
  std::cout << "filter lookup: " << "Camilo " << new_b->lookup("Camilo") << "\n";
  std::cout << "filter lookup: " << "Kenny " << new_b->lookup("Kenny") << "\n";
  std::cout << "filter lookup: " << "Nova " << new_b->lookup("Nova") << "\n";
  std::cout << "filter lookup: " << "Robin " << new_b->lookup("Robin") << "\n";
  std::cout << "filter lookup: " << "Rudy " << new_b->lookup("Rudy") << "\n";
  std::cout << "filter lookup: " << "Van " << new_b->lookup("Van") << "\n";
  std::cout << "filter lookup: " << "Bjorn " << new_b->lookup("Bjorn") << "\n";
  std::cout << "filter lookup: " << "Brodie " << new_b->lookup("Brodie") << "\n";
  std::cout << "filter lookup: " << "Mac " << new_b->lookup("Mac") << "\n";
  std::cout << "filter lookup: " << "Jacoby " << new_b->lookup("Jacoby") << "\n";
  std::cout << "filter lookup: " << "Sekani " << new_b->lookup("Sekani") << "\n";
  std::cout << "filter lookup: " << "Vivaan " << new_b->lookup("Vivaan") << "\n";
  std::cout << "filter lookup: " << "Blaine " << new_b->lookup("Blaine") << "\n";
  std::cout << "filter lookup: " << "Ira " << new_b->lookup("Ira") << "\n";
  std::cout << "filter lookup: " << "Ameer " << new_b->lookup("Ameer") << "\n";
  std::cout << "filter lookup: " << "Dominik " << new_b->lookup("Dominik") << "\n";
  std::cout << "filter lookup: " << "Alaric " << new_b->lookup("Alaric") << "\n";
  std::cout << "filter lookup: " << "Dane " << new_b->lookup("Dane") << "\n";
  std::cout << "filter lookup: " << "Jeremias " << new_b->lookup("Jeremias") << "\n";
  std::cout << "filter lookup: " << "Kyng " << new_b->lookup("Kyng") << "\n";
  std::cout << "filter lookup: " << "Reginald " << new_b->lookup("Reginald") << "\n";
  std::cout << "filter lookup: " << "Bobby " << new_b->lookup("Bobby") << "\n";
  std::cout << "filter lookup: " << "Kabir " << new_b->lookup("Kabir") << "\n";
  std::cout << "filter lookup: " << "Jairo " << new_b->lookup("Jairo") << "\n";
  std::cout << "filter lookup: " << "Alexzander " << new_b->lookup("Alexzander") << "\n";
  std::cout << "filter lookup: " << "Benicio " << new_b->lookup("Benicio") << "\n";
  std::cout << "filter lookup: " << "Vance " << new_b->lookup("Vance") << "\n";
  std::cout << "filter lookup: " << "Wallace " << new_b->lookup("Wallace") << "\n";
  std::cout << "filter lookup: " << "Zavier " << new_b->lookup("Zavier") << "\n";
  std::cout << "filter lookup: " << "Billy " << new_b->lookup("Billy") << "\n";
  std::cout << "filter lookup: " << "Callahan " << new_b->lookup("Callahan") << "\n";
  std::cout << "filter lookup: " << "Dakari " << new_b->lookup("Dakari") << "\n";
  std::cout << "filter lookup: " << "Gerald " << new_b->lookup("Gerald") << "\n";
  std::cout << "filter lookup: " << "Turner " << new_b->lookup("Turner") << "\n";
  std::cout << "filter lookup: " << "Bear " << new_b->lookup("Bear") << "\n";
  std::cout << "filter lookup: " << "Jabari " << new_b->lookup("Jabari") << "\n";
  std::cout << "filter lookup: " << "Cory " << new_b->lookup("Cory") << "\n";
  std::cout << "filter lookup: " << "Fox " << new_b->lookup("Fox") << "\n";
  std::cout << "filter lookup: " << "Harlem " << new_b->lookup("Harlem") << "\n";
  std::cout << "filter lookup: " << "Jakari " << new_b->lookup("Jakari") << "\n";
  std::cout << "filter lookup: " << "Jeffery " << new_b->lookup("Jeffery") << "\n";
  std::cout << "filter lookup: " << "Maxton " << new_b->lookup("Maxton") << "\n";
  std::cout << "filter lookup: " << "Ronnie " << new_b->lookup("Ronnie") << "\n";
  std::cout << "filter lookup: " << "Yisroel " << new_b->lookup("Yisroel") << "\n";
  std::cout << "filter lookup: " << "Zakai " << new_b->lookup("Zakai") << "\n";
  std::cout << "filter lookup: " << "Bridger " << new_b->lookup("Bridger") << "\n";
  std::cout << "filter lookup: " << "Remi " << new_b->lookup("Remi") << "\n";
  std::cout << "filter lookup: " << "Arian " << new_b->lookup("Arian") << "\n";
  std::cout << "filter lookup: " << "Blaze " << new_b->lookup("Blaze") << "\n";
  std::cout << "filter lookup: " << "Forest " << new_b->lookup("Forest") << "\n";
  std::cout << "filter lookup: " << "Genesis " << new_b->lookup("Genesis") << "\n";
  std::cout << "filter lookup: " << "Jerome " << new_b->lookup("Jerome") << "\n";
  std::cout << "filter lookup: " << "Reuben " << new_b->lookup("Reuben") << "\n";
  std::cout << "filter lookup: " << "Wesson " << new_b->lookup("Wesson") << "\n";
  std::cout << "filter lookup: " << "Anders " << new_b->lookup("Anders") << "\n";
  std::cout << "filter lookup: " << "Banks " << new_b->lookup("Banks") << "\n";
  std::cout << "filter lookup: " << "Calum " << new_b->lookup("Calum") << "\n";
  std::cout << "filter lookup: " << "Dayton " << new_b->lookup("Dayton") << "\n";
  std::cout << "filter lookup: " << "Kylen " << new_b->lookup("Kylen") << "\n";
  std::cout << "filter lookup: " << "Dangelo " << new_b->lookup("Dangelo") << "\n";
  std::cout << "filter lookup: " << "Emir " << new_b->lookup("Emir") << "\n";
  std::cout << "filter lookup: " << "Malakhi " << new_b->lookup("Malakhi") << "\n";
  std::cout << "filter lookup: " << "Salem " << new_b->lookup("Salem") << "\n";
  std::cout << "filter lookup: " << "Blaise " << new_b->lookup("Blaise") << "\n";
  std::cout << "filter lookup: " << "Tru " << new_b->lookup("Tru") << "\n";
  std::cout << "filter lookup: " << "Boden " << new_b->lookup("Boden") << "\n";
  std::cout << "filter lookup: " << "Kolten " << new_b->lookup("Kolten") << "\n";
  std::cout << "filter lookup: " << "Kylo " << new_b->lookup("Kylo") << "\n";
  std::cout << "filter lookup: " << "Aries " << new_b->lookup("Aries") << "\n";
  std::cout << "filter lookup: " << "Henrik " << new_b->lookup("Henrik") << "\n";
  std::cout << "filter lookup: " << "Kalel " << new_b->lookup("Kalel") << "\n";
  std::cout << "filter lookup: " << "Landry " << new_b->lookup("Landry") << "\n";
  std::cout << "filter lookup: " << "Marcellus " << new_b->lookup("Marcellus") << "\n";
  std::cout << "filter lookup: " << "Zahir " << new_b->lookup("Zahir") << "\n";
  std::cout << "filter lookup: " << "Lyle " << new_b->lookup("Lyle") << "\n";
  std::cout << "filter lookup: " << "Dario " << new_b->lookup("Dario") << "\n";
  std::cout << "filter lookup: " << "Rene " << new_b->lookup("Rene") << "\n";
  std::cout << "filter lookup: " << "Terrance " << new_b->lookup("Terrance") << "\n";
  std::cout << "filter lookup: " << "Xzavier " << new_b->lookup("Xzavier") << "\n";
  std::cout << "filter lookup: " << "Alfonso " << new_b->lookup("Alfonso") << "\n";
  std::cout << "filter lookup: " << "Darian " << new_b->lookup("Darian") << "\n";
  std::cout << "filter lookup: " << "Kylian " << new_b->lookup("Kylian") << "\n";
  std::cout << "filter lookup: " << "Maison " << new_b->lookup("Maison") << "\n";
  std::cout << "filter lookup: " << "Foster " << new_b->lookup("Foster") << "\n";
  std::cout << "filter lookup: " << "Keenan " << new_b->lookup("Keenan") << "\n";
  std::cout << "filter lookup: " << "Yahya " << new_b->lookup("Yahya") << "\n";
  std::cout << "filter lookup: " << "Heath " << new_b->lookup("Heath") << "\n";
  std::cout << "filter lookup: " << "Javion " << new_b->lookup("Javion") << "\n";
  std::cout << "filter lookup: " << "Jericho " << new_b->lookup("Jericho") << "\n";
  std::cout << "filter lookup: " << "Aziel " << new_b->lookup("Aziel") << "\n";
  std::cout << "filter lookup: " << "Darwin " << new_b->lookup("Darwin") << "\n";
  std::cout << "filter lookup: " << "Marquis " << new_b->lookup("Marquis") << "\n";
  std::cout << "filter lookup: " << "Mylo " << new_b->lookup("Mylo") << "\n";
  std::cout << "filter lookup: " << "Ambrose " << new_b->lookup("Ambrose") << "\n";
  std::cout << "filter lookup: " << "Anakin " << new_b->lookup("Anakin") << "\n";
  std::cout << "filter lookup: " << "Jordy " << new_b->lookup("Jordy") << "\n";
  std::cout << "filter lookup: " << "Juelz " << new_b->lookup("Juelz") << "\n";
  std::cout << "filter lookup: " << "Toby " << new_b->lookup("Toby") << "\n";
  std::cout << "filter lookup: " << "Yael " << new_b->lookup("Yael") << "\n";
  std::cout << "filter lookup: " << "Azrael " << new_b->lookup("Azrael") << "\n";
  std::cout << "filter lookup: " << "Brentley " << new_b->lookup("Brentley") << "\n";
  std::cout << "filter lookup: " << "Tristian " << new_b->lookup("Tristian") << "\n";
  std::cout << "filter lookup: " << "Bode " << new_b->lookup("Bode") << "\n";
  std::cout << "filter lookup: " << "Jovanni " << new_b->lookup("Jovanni") << "\n";
  std::cout << "filter lookup: " << "Santos " << new_b->lookup("Santos") << "\n";
  std::cout << "filter lookup: " << "Alistair " << new_b->lookup("Alistair") << "\n";
  std::cout << "filter lookup: " << "Braydon " << new_b->lookup("Braydon") << "\n";
  std::cout << "filter lookup: " << "Kamdyn " << new_b->lookup("Kamdyn") << "\n";
  std::cout << "filter lookup: " << "Marc " << new_b->lookup("Marc") << "\n";
  std::cout << "filter lookup: " << "Mayson " << new_b->lookup("Mayson") << "\n";
  std::cout << "filter lookup: " << "Niklaus " << new_b->lookup("Niklaus") << "\n";
  std::cout << "filter lookup: " << "Simeon " << new_b->lookup("Simeon") << "\n";
  std::cout << "filter lookup: " << "Colter " << new_b->lookup("Colter") << "\n";
  std::cout << "filter lookup: " << "Davion " << new_b->lookup("Davion") << "\n";
  std::cout << "filter lookup: " << "Leroy " << new_b->lookup("Leroy") << "\n";
  std::cout << "filter lookup: " << "Ayan " << new_b->lookup("Ayan") << "\n";
  std::cout << "filter lookup: " << "Dilan " << new_b->lookup("Dilan") << "\n";
  std::cout << "filter lookup: " << "Ephraim " << new_b->lookup("Ephraim") << "\n";
  std::cout << "filter lookup: " << "Anson " << new_b->lookup("Anson") << "\n";
  std::cout << "filter lookup: " << "Merrick " << new_b->lookup("Merrick") << "\n";
  std::cout << "filter lookup: " << "Wes " << new_b->lookup("Wes") << "\n";
  std::cout << "filter lookup: " << "Will " << new_b->lookup("Will") << "\n";
  std::cout << "filter lookup: " << "Jaxen " << new_b->lookup("Jaxen") << "\n";
  std::cout << "filter lookup: " << "Maxim " << new_b->lookup("Maxim") << "\n";
  std::cout << "filter lookup: " << "Howard " << new_b->lookup("Howard") << "\n";
  std::cout << "filter lookup: " << "Jad " << new_b->lookup("Jad") << "\n";
  std::cout << "filter lookup: " << "Jesiah " << new_b->lookup("Jesiah") << "\n";
  std::cout << "filter lookup: " << "Ignacio " << new_b->lookup("Ignacio") << "\n";
  std::cout << "filter lookup: " << "Zyon " << new_b->lookup("Zyon") << "\n";
  std::cout << "filter lookup: " << "Ahmir " << new_b->lookup("Ahmir") << "\n";
  std::cout << "filter lookup: " << "Jair " << new_b->lookup("Jair") << "\n";
  std::cout << "filter lookup: " << "Mustafa " << new_b->lookup("Mustafa") << "\n";
  std::cout << "filter lookup: " << "Jermaine " << new_b->lookup("Jermaine") << "\n";
  std::cout << "filter lookup: " << "Yadiel " << new_b->lookup("Yadiel") << "\n";
  std::cout << "filter lookup: " << "Aayan " << new_b->lookup("Aayan") << "\n";
  std::cout << "filter lookup: " << "Dhruv " << new_b->lookup("Dhruv") << "\n";
  std::cout << "filter lookup: " << "Seven " << new_b->lookup("Seven") << "\n";
  std::cout << "filter lookup: " << "Stone " << new_b->lookup("Stone") << "\n";
  std::cout << "filter lookup: " << "Rom " << new_b->lookup("Rom") << "\n";
  return 0;
}
